using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.Runtime;
using Autodesk.Civil.ApplicationServices;
using AcApplication = Autodesk.AutoCAD.ApplicationServices.Core.Application;
using CivilAlignment = Autodesk.Civil.DatabaseServices.Alignment;
using CivilNetwork = Autodesk.Civil.DatabaseServices.Network;
using CivilPipe = Autodesk.Civil.DatabaseServices.Pipe;
using CivilStructure = Autodesk.Civil.DatabaseServices.Structure;
using CivilPolylineOptions = Autodesk.Civil.DatabaseServices.PolylineOptions;

[assembly: CommandClass(typeof(CETools.Civil3D.SewerBranchAlignmentCommands))]

namespace CETools.Civil3D
{
    /// <summary>
    /// Creates one siteless Civil 3D alignment for each CE-sequenced sewer branch
    /// and places the visible branch name in plan. Re-running the command replaces
    /// only alignments and labels previously generated by CE Tools.
    /// </summary>
    public sealed class SewerBranchAlignmentCommands
    {
        private const string RegAppName = "CE_TOOLS_SEWALIGN";
        private const string AlignmentLayerName = "CE-SEWER-ALIGNMENT";
        private const double GeometryTolerance = 1e-8;
        private const int CurvedPipeSegments = 12;

        private static readonly Regex PipeNamePattern = new Regex(
            @"^P(?<branch>\d+)\.(?<sequence>\d+)$",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        private static readonly Regex BranchNamePattern = new Regex(
            @"^Branch\s*-\s*(?<branch>\d+)$",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        [CommandMethod(
            "CE_TOOLS",
            "CE_SEWALIGN",
            CommandFlags.Modal | CommandFlags.Redraw | CommandFlags.UsePickSet)]
        public void CreateBranchAlignments()
        {
            Document document = AcApplication.DocumentManager.MdiActiveDocument;
            if (document == null)
            {
                return;
            }

            Editor editor = document.Editor;
            Database database = document.Database;
            CivilDocument civilDocument = CivilApplication.ActiveDocument;
            if (civilDocument == null)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled. No active Civil 3D document is available.");
                return;
            }

            PromptSelectionResult selection = editor.SelectImplied();
            if (selection.Status != PromptStatus.OK ||
                selection.Value == null ||
                selection.Value.Count == 0)
            {
                var options = new PromptSelectionOptions
                {
                    MessageForAdding =
                        "\nSelect one or more CE-sequenced sewer pipes or structures: ",
                    AllowDuplicates = false,
                    RejectObjectsFromNonCurrentSpace = true
                };
                selection = editor.GetSelection(options);
            }

            if (selection.Status != PromptStatus.OK ||
                selection.Value == null ||
                selection.Value.Count == 0)
            {
                return;
            }

            List<ObjectId> networkIds;
            int unsupported;
            try
            {
                ReadSelectedNetworks(
                    database,
                    selection.Value.GetObjectIds(),
                    out networkIds,
                    out unsupported);
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled while reading the selection: " +
                    exception.Message);
                return;
            }

            if (networkIds.Count == 0)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN: select at least one Civil 3D gravity-network pipe or structure.");
                return;
            }

            List<NetworkAlignmentPlan> plans;
            try
            {
                using (Transaction transaction =
                    database.TransactionManager.StartTransaction())
                {
                    plans = networkIds
                        .OrderBy(id => id.Handle.Value)
                        .Select(id => BuildNetworkPlan(id, transaction))
                        .ToList();
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage("\nCE_SEWALIGN cancelled. " + exception.Message);
                return;
            }

            int branchCount = plans.Sum(plan => plan.Branches.Count);
            editor.WriteMessage(
                "\nCE_SEWALIGN preview: networks={0}; branches={1}; unsupported selections ignored={2}.",
                plans.Count,
                branchCount,
                unsupported);

            foreach (NetworkAlignmentPlan plan in plans)
            {
                editor.WriteMessage("\n  Network: {0}", plan.NetworkName);
                foreach (BranchAlignmentPlan branch in plan.Branches)
                {
                    editor.WriteMessage(
                        "\n    {0}: pipes={1}; structures={2}; sampled vertices={3}; alignment direction=high cover to low cover",
                        branch.BranchName,
                        branch.PipeIds.Count,
                        branch.StructureIds.Count,
                        branch.PlanPoints.Count);
                }
            }

            if (!Confirm(
                    editor,
                    "Create or refresh the sewer branch alignments and plan labels"))
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled. No alignments or labels were changed.");
                return;
            }

            try
            {
                int alignmentsCreated;
                int labelsCreated;
                CreateAlignmentsAndLabels(
                    database,
                    civilDocument,
                    plans,
                    out alignmentsCreated,
                    out labelsCreated);

                editor.WriteMessage(
                    "\nCE_SEWALIGN complete. Alignments created/refreshed: {0}; branch-name labels placed: {1}.",
                    alignmentsCreated,
                    labelsCreated);
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled. The transaction was not committed: " +
                    exception.Message);
            }
        }

        private static void ReadSelectedNetworks(
            Database database,
            IEnumerable<ObjectId> selectedIds,
            out List<ObjectId> networkIds,
            out int unsupported)
        {
            var ids = new HashSet<ObjectId>();
            unsupported = 0;

            using (Transaction transaction =
                database.TransactionManager.StartTransaction())
            {
                foreach (ObjectId selectedId in selectedIds)
                {
                    DBObject selected = transaction.GetObject(
                        selectedId,
                        OpenMode.ForRead,
                        false);

                    var pipe = selected as CivilPipe;
                    if (pipe != null && !pipe.NetworkId.IsNull)
                    {
                        ids.Add(pipe.NetworkId);
                        continue;
                    }

                    var structure = selected as CivilStructure;
                    if (structure != null && !structure.NetworkId.IsNull)
                    {
                        ids.Add(structure.NetworkId);
                        continue;
                    }

                    unsupported++;
                }
            }

            networkIds = ids.ToList();
        }

        private static NetworkAlignmentPlan BuildNetworkPlan(
            ObjectId networkId,
            Transaction transaction)
        {
            var network = transaction.GetObject(
                networkId,
                OpenMode.ForRead,
                false) as CivilNetwork;
            if (network == null)
            {
                throw new InvalidOperationException(
                    "A selected part does not resolve to a gravity pipe network.");
            }

            if (network.IsReferenceObject)
            {
                throw new InvalidOperationException(
                    "Referenced network '" + network.Name +
                    "' cannot receive local branch alignments.");
            }

            var groupedPipes = new Dictionary<int, List<BranchPipeRecord>>();
            foreach (ObjectId pipeId in network.GetPipeIds())
            {
                var pipe = transaction.GetObject(
                    pipeId,
                    OpenMode.ForRead,
                    false) as CivilPipe;
                if (pipe == null)
                {
                    continue;
                }

                int branchNumber;
                int sequenceNumber;
                if (!TryReadBranch(pipe, out branchNumber, out sequenceNumber))
                {
                    continue;
                }

                if (pipe.StartStructureId.IsNull || pipe.EndStructureId.IsNull)
                {
                    throw new InvalidOperationException(
                        "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                        " contains an unconnected pipe.");
                }

                List<BranchPipeRecord> records;
                if (!groupedPipes.TryGetValue(branchNumber, out records))
                {
                    records = new List<BranchPipeRecord>();
                    groupedPipes[branchNumber] = records;
                }

                records.Add(new BranchPipeRecord(
                    pipeId,
                    pipe.StartStructureId,
                    pipe.EndStructureId,
                    sequenceNumber));
            }

            if (groupedPipes.Count == 0)
            {
                throw new InvalidOperationException(
                    "Network '" + network.Name +
                    "' contains no CE-sequenced branch pipes. Run CE_SEWSEQ first.");
            }

            var branches = new List<BranchAlignmentPlan>();
            foreach (KeyValuePair<int, List<BranchPipeRecord>> pair in
                groupedPipes.OrderBy(item => item.Key))
            {
                branches.Add(BuildBranchPlan(
                    networkId,
                    pair.Key,
                    pair.Value,
                    transaction));
            }

            return new NetworkAlignmentPlan(
                networkId,
                network.Name,
                branches);
        }

        private static bool TryReadBranch(
            CivilPipe pipe,
            out int branchNumber,
            out int sequenceNumber)
        {
            branchNumber = 0;
            sequenceNumber = int.MaxValue;

            Match pipeMatch = PipeNamePattern.Match(pipe.Name ?? string.Empty);
            if (pipeMatch.Success)
            {
                return int.TryParse(
                           pipeMatch.Groups["branch"].Value,
                           NumberStyles.None,
                           CultureInfo.InvariantCulture,
                           out branchNumber) &&
                       int.TryParse(
                           pipeMatch.Groups["sequence"].Value,
                           NumberStyles.None,
                           CultureInfo.InvariantCulture,
                           out sequenceNumber);
            }

            Match branchMatch = BranchNamePattern.Match(
                pipe.Description ?? string.Empty);
            if (!branchMatch.Success ||
                !int.TryParse(
                    branchMatch.Groups["branch"].Value,
                    NumberStyles.None,
                    CultureInfo.InvariantCulture,
                    out branchNumber))
            {
                return false;
            }

            return true;
        }

        private static BranchAlignmentPlan BuildBranchPlan(
            ObjectId networkId,
            int branchNumber,
            IReadOnlyList<BranchPipeRecord> pipeRecords,
            Transaction transaction)
        {
            var adjacency = new Dictionary<ObjectId, List<BranchPipeRecord>>();
            foreach (BranchPipeRecord pipe in pipeRecords)
            {
                AddPipe(adjacency, pipe.StartStructureId, pipe);
                AddPipe(adjacency, pipe.EndStructureId, pipe);
            }

            if (adjacency.Any(item => item.Value.Count > 2))
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " is not a single continuous path.");
            }

            List<ObjectId> endpoints = adjacency
                .Where(item => item.Value.Count == 1)
                .Select(item => item.Key)
                .ToList();
            if (endpoints.Count != 2)
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " must have exactly two endpoints.");
            }

            ObjectId startId = endpoints
                .OrderByDescending(id => GetRimElevation(id, transaction))
                .ThenBy(id => id.Handle.Value)
                .First();

            var unusedPipes = new HashSet<ObjectId>(
                pipeRecords.Select(record => record.PipeId));
            var orderedStructures = new List<ObjectId>();
            var orderedPipes = new List<ObjectId>();
            ObjectId current = startId;

            while (true)
            {
                orderedStructures.Add(current);
                BranchPipeRecord next = adjacency[current]
                    .Where(record => unusedPipes.Contains(record.PipeId))
                    .OrderBy(record => record.SequenceNumber)
                    .ThenBy(record => record.PipeId.Handle.Value)
                    .FirstOrDefault();
                if (next == null)
                {
                    break;
                }

                unusedPipes.Remove(next.PipeId);
                orderedPipes.Add(next.PipeId);
                current = next.Other(current);
            }

            if (unusedPipes.Count != 0 ||
                orderedPipes.Count != pipeRecords.Count ||
                orderedStructures.Count != orderedPipes.Count + 1)
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " contains disconnected or ambiguous pipe geometry.");
            }

            List<Point3d> planPoints = BuildPlanPoints(
                orderedStructures,
                orderedPipes,
                transaction);
            if (planPoints.Count < 2)
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " does not contain enough plan geometry for an alignment.");
            }

            return new BranchAlignmentPlan(
                networkId,
                branchNumber,
                orderedStructures,
                orderedPipes,
                planPoints);
        }

        private static void AddPipe(
            IDictionary<ObjectId, List<BranchPipeRecord>> adjacency,
            ObjectId structureId,
            BranchPipeRecord pipe)
        {
            List<BranchPipeRecord> list;
            if (!adjacency.TryGetValue(structureId, out list))
            {
                list = new List<BranchPipeRecord>();
                adjacency[structureId] = list;
            }

            list.Add(pipe);
        }

        private static double GetRimElevation(
            ObjectId structureId,
            Transaction transaction)
        {
            var structure = transaction.GetObject(
                structureId,
                OpenMode.ForRead,
                false) as CivilStructure;
            if (structure == null)
            {
                return double.MinValue;
            }

            double rim = structure.RimElevation;
            return double.IsNaN(rim) || double.IsInfinity(rim)
                ? structure.Position.Z
                : rim;
        }

        private static List<Point3d> BuildPlanPoints(
            IReadOnlyList<ObjectId> structureIds,
            IReadOnlyList<ObjectId> pipeIds,
            Transaction transaction)
        {
            var points = new List<Point3d>();

            for (int index = 0; index < pipeIds.Count; index++)
            {
                var pipe = transaction.GetObject(
                    pipeIds[index],
                    OpenMode.ForRead,
                    false) as CivilPipe;
                if (pipe == null)
                {
                    continue;
                }

                ObjectId fromStructureId = structureIds[index];
                bool forward = pipe.StartStructureId == fromStructureId;
                int segmentCount = IsCurvedPipe(pipe)
                    ? CurvedPipeSegments
                    : 1;

                for (int segment = 0; segment <= segmentCount; segment++)
                {
                    double fraction = segment / (double)segmentCount;
                    double parameter = forward ? fraction : 1.0 - fraction;
                    Point3d point = pipe.GetPointAtParam(parameter);
                    AddDistinctPlanPoint(points, point);
                }
            }

            return points;
        }

        private static bool IsCurvedPipe(CivilPipe pipe)
        {
            try
            {
                return pipe.Curve2d != null;
            }
            catch (InvalidOperationException)
            {
                return false;
            }
        }

        private static void AddDistinctPlanPoint(
            ICollection<Point3d> points,
            Point3d point)
        {
            Point3d planPoint = new Point3d(point.X, point.Y, 0.0);
            Point3d last = points.Count == 0
                ? Point3d.Origin
                : points.Last();

            if (points.Count == 0 || last.DistanceTo(planPoint) > GeometryTolerance)
            {
                points.Add(planPoint);
            }
        }

        private static void CreateAlignmentsAndLabels(
            Database database,
            CivilDocument civilDocument,
            IReadOnlyList<NetworkAlignmentPlan> plans,
            out int alignmentsCreated,
            out int labelsCreated)
        {
            alignmentsCreated = 0;
            labelsCreated = 0;

            using (Transaction transaction =
                database.TransactionManager.StartTransaction())
            {
                EnsureRegApp(database, transaction);
                ObjectId layerId = GetOrCreateLayer(database, transaction);
                ObjectId alignmentStyleId = GetFirstStyleId(
                    civilDocument.Styles.AlignmentStyles,
                    "alignment style");
                ObjectId labelSetStyleId = GetFirstStyleId(
                    civilDocument.Styles.LabelSetStyles.AlignmentLabelSetStyles,
                    "alignment label-set style");

                BlockTable blockTable = (BlockTable)transaction.GetObject(
                    database.BlockTableId,
                    OpenMode.ForRead,
                    false);
                BlockTableRecord modelSpace = (BlockTableRecord)transaction.GetObject(
                    blockTable[BlockTableRecord.ModelSpace],
                    OpenMode.ForWrite,
                    false);

                var reservedNames = new HashSet<string>(
                    StringComparer.OrdinalIgnoreCase);

                foreach (NetworkAlignmentPlan plan in plans)
                {
                    string networkHandle = plan.NetworkId.Handle.ToString();
                    foreach (BranchAlignmentPlan branch in plan.Branches)
                    {
                        string branchKey = BuildBranchKey(
                            networkHandle,
                            branch.BranchName);

                        RemoveExistingGeneratedObjects(
                            civilDocument,
                            modelSpace,
                            branchKey,
                            transaction);

                        string alignmentName = ResolveAlignmentName(
                            civilDocument,
                            plan.NetworkName,
                            branch.BranchName,
                            reservedNames,
                            transaction);

                        ObjectId polylineId = AddSourcePolyline(
                            database,
                            modelSpace,
                            branch.PlanPoints,
                            layerId,
                            transaction);

                        var polylineOptions = new CivilPolylineOptions
                        {
                            AddCurvesBetweenTangents = false,
                            EraseExistingEntities = true,
                            PlineId = polylineId
                        };

                        ObjectId alignmentId = CivilAlignment.Create(
                            civilDocument,
                            polylineOptions,
                            alignmentName,
                            ObjectId.Null,
                            layerId,
                            alignmentStyleId,
                            labelSetStyleId);

                        var alignment = transaction.GetObject(
                            alignmentId,
                            OpenMode.ForWrite,
                            false) as CivilAlignment;
                        if (alignment == null)
                        {
                            throw new InvalidOperationException(
                                "Civil 3D did not return the created sewer branch alignment.");
                        }

                        alignment.Description =
                            "CE sewer alignment - " + branch.BranchName;
                        alignment.XData = BuildTag(branchKey, "Alignment");
                        alignmentsCreated++;

                        Point3d labelPoint = GetMidpoint(branch.PlanPoints);
                        var label = new MText();
                        label.SetDatabaseDefaults(database);
                        label.LayerId = layerId;
                        label.Location = labelPoint;
                        label.Attachment = AttachmentPoint.MiddleCenter;
                        label.TextHeight = GetTextHeight(database);
                        label.Contents = branch.BranchName;
                        label.BackgroundFill = true;
                        label.UseBackgroundColor = true;
                        label.XData = BuildTag(branchKey, "Label");
                        modelSpace.AppendEntity(label);
                        transaction.AddNewlyCreatedDBObject(label, true);
                        labelsCreated++;
                    }
                }

                transaction.Commit();
            }
        }

        private static ObjectId GetFirstStyleId(
            IEnumerable<ObjectId> styleIds,
            string description)
        {
            ObjectId id = styleIds.FirstOrDefault();
            if (id.IsNull)
            {
                throw new InvalidOperationException(
                    "The drawing contains no " + description + ".");
            }

            return id;
        }

        private static ObjectId AddSourcePolyline(
            Database database,
            BlockTableRecord modelSpace,
            IReadOnlyList<Point3d> points,
            ObjectId layerId,
            Transaction transaction)
        {
            var polyline = new Polyline(points.Count);
            polyline.SetDatabaseDefaults(database);
            polyline.LayerId = layerId;

            for (int index = 0; index < points.Count; index++)
            {
                polyline.AddVertexAt(
                    index,
                    new Point2d(points[index].X, points[index].Y),
                    0.0,
                    0.0,
                    0.0);
            }

            modelSpace.AppendEntity(polyline);
            transaction.AddNewlyCreatedDBObject(polyline, true);
            return polyline.ObjectId;
        }

        private static string ResolveAlignmentName(
            CivilDocument civilDocument,
            string networkName,
            string branchName,
            ISet<string> reservedNames,
            Transaction transaction)
        {
            var existing = new HashSet<string>(
                StringComparer.OrdinalIgnoreCase);
            foreach (ObjectId alignmentId in civilDocument.GetAlignmentIds())
            {
                var alignment = transaction.GetObject(
                    alignmentId,
                    OpenMode.ForRead,
                    false) as CivilAlignment;
                if (alignment != null)
                {
                    existing.Add(alignment.Name);
                }
            }

            string preferred = branchName;
            if (!existing.Contains(preferred) && reservedNames.Add(preferred))
            {
                return preferred;
            }

            string baseName = SanitizeName(networkName) + " - " + branchName;
            string candidate = baseName;
            int suffix = 2;
            while (existing.Contains(candidate) || !reservedNames.Add(candidate))
            {
                candidate = baseName + " (" +
                    suffix.ToString(CultureInfo.InvariantCulture) + ")";
                suffix++;
            }

            return candidate;
        }

        private static string SanitizeName(string value)
        {
            string text = string.IsNullOrWhiteSpace(value)
                ? "Sewer Network"
                : value.Trim();
            foreach (char invalid in new[] { '<', '>', '/', '\\', '"', ':', ';', '?', '*', '|', ',', '=' })
            {
                text = text.Replace(invalid, '-');
            }

            return text;
        }

        private static void RemoveExistingGeneratedObjects(
            CivilDocument civilDocument,
            BlockTableRecord modelSpace,
            string branchKey,
            Transaction transaction)
        {
            foreach (ObjectId alignmentId in civilDocument.GetAlignmentIds())
            {
                DBObject alignment = transaction.GetObject(
                    alignmentId,
                    OpenMode.ForRead,
                    false);
                if (HasTag(alignment, branchKey, "Alignment"))
                {
                    alignment.UpgradeOpen();
                    alignment.Erase();
                }
            }

            foreach (ObjectId entityId in modelSpace)
            {
                DBObject entity = transaction.GetObject(
                    entityId,
                    OpenMode.ForRead,
                    false);
                if (HasTag(entity, branchKey, "Label"))
                {
                    entity.UpgradeOpen();
                    entity.Erase();
                }
            }
        }

        private static bool HasTag(
            DBObject databaseObject,
            string branchKey,
            string objectType)
        {
            using (ResultBuffer data =
                databaseObject.GetXDataForApplication(RegAppName))
            {
                if (data == null)
                {
                    return false;
                }

                string[] values = data.AsArray()
                    .Where(value => value.TypeCode ==
                        (int)DxfCode.ExtendedDataAsciiString)
                    .Select(value => value.Value as string)
                    .Where(value => value != null)
                    .ToArray();

                return values.Length >= 2 &&
                       string.Equals(values[0], branchKey, StringComparison.Ordinal) &&
                       string.Equals(values[1], objectType, StringComparison.Ordinal);
            }
        }

        private static ResultBuffer BuildTag(
            string branchKey,
            string objectType)
        {
            return new ResultBuffer(
                new TypedValue(
                    (int)DxfCode.ExtendedDataRegAppName,
                    RegAppName),
                new TypedValue(
                    (int)DxfCode.ExtendedDataAsciiString,
                    branchKey),
                new TypedValue(
                    (int)DxfCode.ExtendedDataAsciiString,
                    objectType));
        }

        private static string BuildBranchKey(
            string networkHandle,
            string branchName)
        {
            return networkHandle + "|" + branchName;
        }

        private static ObjectId GetOrCreateLayer(
            Database database,
            Transaction transaction)
        {
            LayerTable layers = (LayerTable)transaction.GetObject(
                database.LayerTableId,
                OpenMode.ForRead,
                false);
            if (layers.Has(AlignmentLayerName))
            {
                ObjectId existingId = layers[AlignmentLayerName];
                var existing = transaction.GetObject(
                    existingId,
                    OpenMode.ForRead,
                    false) as LayerTableRecord;
                if (existing != null && existing.IsLocked)
                {
                    throw new InvalidOperationException(
                        "Layer '" + AlignmentLayerName + "' is locked.");
                }

                return existingId;
            }

            layers.UpgradeOpen();
            var layer = new LayerTableRecord
            {
                Name = AlignmentLayerName
            };
            ObjectId layerId = layers.Add(layer);
            transaction.AddNewlyCreatedDBObject(layer, true);
            return layerId;
        }

        private static void EnsureRegApp(
            Database database,
            Transaction transaction)
        {
            RegAppTable applications = (RegAppTable)transaction.GetObject(
                database.RegAppTableId,
                OpenMode.ForRead,
                false);
            if (applications.Has(RegAppName))
            {
                return;
            }

            applications.UpgradeOpen();
            var record = new RegAppTableRecord
            {
                Name = RegAppName
            };
            applications.Add(record);
            transaction.AddNewlyCreatedDBObject(record, true);
        }

        private static Point3d GetMidpoint(IReadOnlyList<Point3d> points)
        {
            double totalLength = 0.0;
            for (int index = 1; index < points.Count; index++)
            {
                totalLength += points[index - 1].DistanceTo(points[index]);
            }

            double target = totalLength * 0.5;
            double travelled = 0.0;
            for (int index = 1; index < points.Count; index++)
            {
                Point3d start = points[index - 1];
                Point3d end = points[index];
                double segmentLength = start.DistanceTo(end);
                if (travelled + segmentLength >= target &&
                    segmentLength > GeometryTolerance)
                {
                    double fraction = (target - travelled) / segmentLength;
                    return start + ((end - start) * fraction);
                }

                travelled += segmentLength;
            }

            return points[points.Count / 2];
        }

        private static double GetTextHeight(Database database)
        {
            double value = database.Textsize;
            return value > 0.0 &&
                   !double.IsNaN(value) &&
                   !double.IsInfinity(value)
                ? value
                : 2.5;
        }

        private static bool Confirm(Editor editor, string message)
        {
            var options = new PromptKeywordOptions(
                "\n" + message + "? [Yes/No] <No>: ")
            {
                AllowNone = true
            };
            options.Keywords.Add("Yes");
            options.Keywords.Add("No");

            PromptResult result = editor.GetKeywords(options);
            return result.Status == PromptStatus.OK &&
                   string.Equals(
                       result.StringResult,
                       "Yes",
                       StringComparison.OrdinalIgnoreCase);
        }

        private sealed class NetworkAlignmentPlan
        {
            public NetworkAlignmentPlan(
                ObjectId networkId,
                string networkName,
                IReadOnlyList<BranchAlignmentPlan> branches)
            {
                NetworkId = networkId;
                NetworkName = networkName ?? string.Empty;
                Branches = branches;
            }

            public ObjectId NetworkId { get; }
            public string NetworkName { get; }
            public IReadOnlyList<BranchAlignmentPlan> Branches { get; }
        }

        private sealed class BranchAlignmentPlan
        {
            public BranchAlignmentPlan(
                ObjectId networkId,
                int branchNumber,
                IReadOnlyList<ObjectId> structureIds,
                IReadOnlyList<ObjectId> pipeIds,
                IReadOnlyList<Point3d> planPoints)
            {
                NetworkId = networkId;
                BranchNumber = branchNumber;
                StructureIds = structureIds;
                PipeIds = pipeIds;
                PlanPoints = planPoints;
            }

            public ObjectId NetworkId { get; }
            public int BranchNumber { get; }
            public string BranchName =>
                "Branch-" + BranchNumber.ToString(CultureInfo.InvariantCulture);
            public IReadOnlyList<ObjectId> StructureIds { get; }
            public IReadOnlyList<ObjectId> PipeIds { get; }
            public IReadOnlyList<Point3d> PlanPoints { get; }
        }

        private sealed class BranchPipeRecord
        {
            public BranchPipeRecord(
                ObjectId pipeId,
                ObjectId startStructureId,
                ObjectId endStructureId,
                int sequenceNumber)
            {
                PipeId = pipeId;
                StartStructureId = startStructureId;
                EndStructureId = endStructureId;
                SequenceNumber = sequenceNumber;
            }

            public ObjectId PipeId { get; }
            public ObjectId StartStructureId { get; }
            public ObjectId EndStructureId { get; }
            public int SequenceNumber { get; }

            public ObjectId Other(ObjectId structureId)
            {
                if (structureId == StartStructureId)
                {
                    return EndStructureId;
                }

                if (structureId == EndStructureId)
                {
                    return StartStructureId;
                }

                throw new InvalidOperationException(
                    "A branch pipe was queried from a structure it does not connect.");
            }
        }
    }
}
