using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.Runtime;
using Autodesk.Civil.ApplicationServices;
using AcApplication = Autodesk.AutoCAD.ApplicationServices.Core.Application;
using CivilAlignment = Autodesk.Civil.DatabaseServices.Alignment;
using CivilNetwork = Autodesk.Civil.DatabaseServices.Network;
using CivilPipe = Autodesk.Civil.DatabaseServices.Pipe;
using CivilStructure = Autodesk.Civil.DatabaseServices.Structure;
using CivilPolylineOptions = Autodesk.Civil.DatabaseServices.PolylineOptions;

[assembly: CommandClass(typeof(CETools.Civil3D.SewerBranchAlignmentCommands))]

namespace CETools.Civil3D
{
    /// <summary>
    /// Creates one siteless Civil 3D alignment for each CE-sequenced sewer branch
    /// and places the visible branch name in plan. Re-running the command replaces
    /// only alignments and labels previously generated by CE Tools.
    /// </summary>
    public sealed class SewerBranchAlignmentCommands
    {
        private const string RegAppName = "CE_TOOLS_SEWALIGN";
        private const string AlignmentLayerName = "CE-SEWER-ALIGNMENT";
        private const double GeometryTolerance = 1e-8;
        private const int CurvedPipeSegments = 12;

        private static readonly Regex PipeNamePattern = new Regex(
            @"^P(?<branch>\d+)\.(?<sequence>\d+)$",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        private static readonly Regex BranchNamePattern = new Regex(
            @"^Branch\s*-\s*(?<branch>\d+)$",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        private static readonly Regex StructureNamePattern = new Regex(
            @"^MH(?<branch>\d+)\.(?<sequence>\d+)$",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        [CommandMethod(
            "CE_TOOLS",
            "CE_SEWALIGN",
            CommandFlags.Modal | CommandFlags.Redraw | CommandFlags.UsePickSet)]
        public void CreateBranchAlignments()
        {
            Document document = AcApplication.DocumentManager.MdiActiveDocument;
            if (document == null)
            {
                return;
            }

            Editor editor = document.Editor;
            Database database = document.Database;
            CivilDocument civilDocument = CivilApplication.ActiveDocument;
            if (civilDocument == null)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled. No active Civil 3D document is available.");
                return;
            }

            List<ObjectId> networkIds;
            int unsupported = 0;
            var scope = new PromptKeywordOptions(
                "\nSewer alignment scope [AllNetworkParts/Select] <AllNetworkParts>: ")
            {
                AllowNone = true
            };
            scope.Keywords.Add("AllNetworkParts");
            scope.Keywords.Add("Select");
            PromptResult scopeResult = editor.GetKeywords(scope);
            if (scopeResult.Status == PromptStatus.Cancel)
                return;

            bool selectManually =
                scopeResult.Status == PromptStatus.OK &&
                string.Equals(
                    scopeResult.StringResult,
                    "Select",
                    StringComparison.OrdinalIgnoreCase);

            try
            {
                if (selectManually)
                {
                    PromptSelectionResult selection =
                        editor.SelectImplied();
                    if (selection.Status != PromptStatus.OK ||
                        selection.Value == null ||
                        selection.Value.Count == 0)
                    {
                        selection = editor.GetSelection(
                            new PromptSelectionOptions
                            {
                                MessageForAdding =
                                    "\nSelect one or more CE-sequenced sewer pipes or structures: ",
                                AllowDuplicates = false,
                                RejectObjectsFromNonCurrentSpace = true
                            });
                    }

                    if (selection.Status != PromptStatus.OK ||
                        selection.Value == null ||
                        selection.Value.Count == 0)
                        return;

                    ReadSelectedNetworks(
                        database,
                        selection.Value.GetObjectIds(),
                        out networkIds,
                        out unsupported);
                }
                else
                {
                    networkIds = ReadAllSequencedSewerNetworks(
                        database,
                        civilDocument);
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled while reading the selection: " +
                    exception.Message);
                return;
            }

            if (networkIds.Count == 0)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN: select at least one Civil 3D gravity-network pipe or structure.");
                return;
            }

            List<NetworkAlignmentPlan> plans;
            try
            {
                using (Transaction transaction =
                    database.TransactionManager.StartTransaction())
                {
                    plans = networkIds
                        .OrderBy(id => id.Handle.Value)
                        .Select(id => BuildNetworkPlan(id, transaction))
                        .ToList();
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage("\nCE_SEWALIGN cancelled. " + exception.Message);
                return;
            }

            int branchCount = plans.Sum(plan => plan.Branches.Count);
            editor.WriteMessage(
                "\nCE_SEWALIGN preview: networks={0}; branches={1}; unsupported selections ignored={2}.",
                plans.Count,
                branchCount,
                unsupported);

            foreach (NetworkAlignmentPlan plan in plans)
            {
                editor.WriteMessage("\n  Network: {0}", plan.NetworkName);
                foreach (BranchAlignmentPlan branch in plan.Branches)
                {
                    editor.WriteMessage(
                        "\n    {0}: pipes={1}; structures={2}; sampled vertices={3}; start structure={4} -> station 0+000",
                        branch.BranchName,
                        branch.PipeIds.Count,
                        branch.StructureIds.Count,
                        branch.PlanPoints.Count,
                        branch.StartStructureName);
                }
            }

            if (!Confirm(
                    editor,
                    "Create or refresh the sewer branch alignments and plan labels"))
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled. No alignments or labels were changed.");
                return;
            }

            try
            {
                int alignmentsCreated;
                int labelsCreated;
                CreateAlignmentsAndLabels(
                    database,
                    civilDocument,
                    plans,
                    out alignmentsCreated,
                    out labelsCreated);

                editor.WriteMessage(
                    "\nCE_SEWALIGN complete. Alignments created/refreshed: {0}; branch-name labels placed: {1}. Every branch is oriented from its resolved P#.1 start structure and verified at station 0+000.",
                    alignmentsCreated,
                    labelsCreated);
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGN cancelled. The transaction was not committed: " +
                    exception.Message);
            }
        }

        [CommandMethod(
            "CE_TOOLS",
            "CE_SEWALIGNSTARTFIX",
            CommandFlags.Modal | CommandFlags.Redraw | CommandFlags.UsePickSet)]
        public void RepairExistingAlignmentStarts()
        {
            Document document = AcApplication.DocumentManager.MdiActiveDocument;
            CivilDocument civilDocument = CivilApplication.ActiveDocument;
            if (document == null || civilDocument == null)
                return;

            Editor editor = document.Editor;
            List<ObjectId> networkIds;
            int unsupported = 0;

            var scope = new PromptKeywordOptions(
                "\nSewer alignment start repair scope [AllNetworkParts/Select] <AllNetworkParts>: ")
            {
                AllowNone = true
            };
            scope.Keywords.Add("AllNetworkParts");
            scope.Keywords.Add("Select");
            PromptResult scopeResult = editor.GetKeywords(scope);
            if (scopeResult.Status == PromptStatus.Cancel)
                return;

            bool selectManually =
                scopeResult.Status == PromptStatus.OK &&
                string.Equals(
                    scopeResult.StringResult,
                    "Select",
                    StringComparison.OrdinalIgnoreCase);

            try
            {
                if (selectManually)
                {
                    PromptSelectionResult selection = editor.SelectImplied();
                    if (selection.Status != PromptStatus.OK ||
                        selection.Value == null ||
                        selection.Value.Count == 0)
                    {
                        selection = editor.GetSelection(
                            new PromptSelectionOptions
                            {
                                MessageForAdding =
                                    "\nSelect sewer pipes/structures whose branch alignments must start at the branch-start structure: ",
                                AllowDuplicates = false,
                                RejectObjectsFromNonCurrentSpace = true
                            });
                    }

                    if (selection.Status != PromptStatus.OK ||
                        selection.Value == null ||
                        selection.Value.Count == 0)
                        return;

                    ReadSelectedNetworks(
                        document.Database,
                        selection.Value.GetObjectIds(),
                        out networkIds,
                        out unsupported);
                }
                else
                {
                    networkIds = ReadAllSequencedSewerNetworks(
                        document.Database,
                        civilDocument);
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGNSTARTFIX cancelled while resolving sewer networks. " +
                    exception.Message);
                return;
            }

            if (networkIds.Count == 0)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGNSTARTFIX: no CE-sequenced sewer networks were found.");
                return;
            }

            List<NetworkAlignmentPlan> plans;
            using (Transaction read =
                document.Database.TransactionManager.StartTransaction())
            {
                plans = networkIds
                    .OrderBy(id => id.Handle.Value)
                    .Select(id => BuildNetworkPlan(id, read))
                    .ToList();
            }

            int checkedAlignments = 0;
            int reversedAlignments = 0;
            int missingAlignments = 0;
            var repaired = new List<string>();

            try
            {
                using (DocumentLock documentLock = document.LockDocument())
                using (Transaction transaction =
                    document.Database.TransactionManager.StartTransaction())
                {
                    foreach (NetworkAlignmentPlan plan in plans)
                    {
                        foreach (BranchAlignmentPlan branch in plan.Branches)
                        {
                            ObjectId alignmentId =
                                ResolveExistingBranchAlignmentId(
                                    civilDocument,
                                    plan,
                                    branch,
                                    transaction);
                            if (alignmentId.IsNull)
                            {
                                missingAlignments++;
                                continue;
                            }

                            CivilAlignment alignment = transaction.GetObject(
                                alignmentId,
                                OpenMode.ForWrite,
                                false) as CivilAlignment;
                            if (alignment == null)
                            {
                                missingAlignments++;
                                continue;
                            }

                            Point2d expected = new Point2d(
                                branch.PlanPoints[0].X,
                                branch.PlanPoints[0].Y);
                            bool reverseNeeded =
                                PlanDistance(
                                    ReadAlignmentStartPoint(alignment),
                                    expected) >
                                PlanDistance(
                                    ReadAlignmentEndPoint(alignment),
                                    expected) + 0.001;

                            EnsureAlignmentDirectionAtBranchStart(
                                alignment,
                                branch.BranchName,
                                branch.StartStructureName,
                                branch.PlanPoints[0]);
                            ForceAlignmentStartStationZero(
                                alignment,
                                branch.BranchName,
                                branch.StartStructureName,
                                branch.PlanPoints[0]);

                            checkedAlignments++;
                            if (reverseNeeded)
                                reversedAlignments++;
                            repaired.Add(
                                branch.BranchName +
                                " -> " +
                                branch.StartStructureName +
                                " = 0+000");
                        }
                    }

                    transaction.Commit();
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWALIGNSTARTFIX cancelled; no repair transaction was committed. " +
                    exception.Message);
                return;
            }

            document.Editor.Regen();
            editor.WriteMessage(
                "\nCE_SEWALIGNSTARTFIX complete. Alignments verified/repaired={0}; reversed={1}; missing/unresolved={2}; unsupported selections ignored={3}.",
                checkedAlignments,
                reversedAlignments,
                missingAlignments,
                unsupported);
            foreach (string item in repaired.Take(20))
                editor.WriteMessage("\n  " + item);
            if (repaired.Count > 20)
                editor.WriteMessage(
                    "\n  ... plus {0} additional branch alignments.",
                    repaired.Count - 20);
        }

        [CommandMethod(
            "CE_TOOLS",
            "CE_SEWBRANCHNAMES",
            CommandFlags.Modal | CommandFlags.Redraw | CommandFlags.UsePickSet)]
        public void RefreshBranchNames()
        {
            Document document =
                AcApplication.DocumentManager.MdiActiveDocument;
            CivilDocument civilDocument =
                CivilApplication.ActiveDocument;
            if (document == null ||
                civilDocument == null)
                return;

            Editor editor = document.Editor;
            Database database = document.Database;
            SewerProductionSettings productionSettings =
                SewerProductionSettings.Read(database);

            var model =
                new ProductionSettingsDialogModel(
                    "CE Tools - Sewer Branch Names",
                    "Add or refresh green Branch-x names like the plan example: centred on each straight sewer branch section, rotated with the pipe run and offset clear above the sewer annotation.");

            model.AddChoice(
                "Scope",
                "01 Branches",
                "Branches to label",
                "All sewer branches",
                "Label every CE-sequenced sewer branch, or only branches from multiple selected sewer pipes/structures.",
                new[]
                {
                    "All sewer branches",
                    "Selected sewer parts"
                });
            model.AddChoice(
                "Side",
                "02 Presentation",
                "Branch-name side",
                "Above",
                "Above matches the requested plan presentation. Below and alternating remain available where drawing congestion requires them.",
                new[]
                {
                    "Above",
                    "Below",
                    "Alternating"
                });
            const string createLayerChoice = "<Create new CE Tools layer>";
            List<string> branchLayerChoices = ReadLayerNames(database);
            if (!branchLayerChoices.Any(name =>
                    string.Equals(
                        name,
                        productionSettings.BranchLabelLayer,
                        StringComparison.OrdinalIgnoreCase)))
                branchLayerChoices.Insert(0, productionSettings.BranchLabelLayer);
            branchLayerChoices.Insert(0, createLayerChoice);
            string branchLayerDefault = branchLayerChoices.Any(name =>
                    string.Equals(
                        name,
                        productionSettings.BranchLabelLayer,
                        StringComparison.OrdinalIgnoreCase))
                ? productionSettings.BranchLabelLayer
                : createLayerChoice;
            model.AddChoice(
                "BranchLayer",
                "02 Presentation",
                "Branch-name layer",
                branchLayerDefault,
                "Select an existing drawing layer, or choose Create new CE Tools layer and type the new layer name below.",
                branchLayerChoices);
            model.AddText(
                "NewBranchLayer",
                "02 Presentation",
                "New CE Tools layer name",
                productionSettings.BranchLabelLayer,
                "Used only when Create new CE Tools layer is selected. The layer is created automatically.");
            model.AddPaperHeight(
                "Height",
                "02 Presentation",
                "Branch-name paper height",
                productionSettings.LabelHeight,
                "Annotative paper height for the green Branch-x names.");
            model.AddPositiveDouble(
                "AboveOffset",
                "02 Presentation",
                "Above offset (paper mm)",
                productionSettings.BranchLabelAboveOffset,
                "Perpendicular paper distance from the sewer centreline when the name is placed above.");
            model.AddPositiveDouble(
                "BelowOffset",
                "02 Presentation",
                "Below offset (paper mm)",
                productionSettings.BranchLabelBelowOffset,
                "Perpendicular paper distance from the sewer centreline when the name is placed below.");
            model.AddPositiveDouble(
                "LongThreshold",
                "03 Long branches",
                "Long straight section threshold (m)",
                productionSettings.BranchLabelLongSectionLength,
                "Each straight run always receives one centred Branch-x name. Runs longer than this also receive extra names at pipe centres.");
            model.AddChoice(
                "LongFrequency",
                "03 Long branches",
                "Long-section repeat frequency",
                productionSettings.BranchLabelLongSectionFrequency,
                "For long straight runs, repeat the branch name at every pipe centre or every second pipe centre.",
                new[]
                {
                    "Every pipe",
                    "Every second pipe"
                });

            if (!DisciplineWorkflowDialogs.EditSettings(model))
                return;

            bool selectManually =
                string.Equals(
                    model.Text("Scope"),
                    "Selected sewer parts",
                    StringComparison.OrdinalIgnoreCase);

            productionSettings.BranchLabelSide =
                model.Text("Side");
            productionSettings.LabelHeight =
                PaperAnnotationScale.NormalizeConfiguredPaperHeight(
                    model.Double(
                        "Height",
                        productionSettings.LabelHeight));
            productionSettings.BranchLabelAboveOffset =
                model.Double(
                    "AboveOffset",
                    productionSettings.BranchLabelAboveOffset);
            productionSettings.BranchLabelBelowOffset =
                model.Double(
                    "BelowOffset",
                    productionSettings.BranchLabelBelowOffset);
            productionSettings.BranchLabelLongSectionLength =
                model.Double(
                    "LongThreshold",
                    productionSettings.BranchLabelLongSectionLength);
            productionSettings.BranchLabelLongSectionFrequency =
                model.Text("LongFrequency");
            string requestedBranchLayer =
                string.Equals(
                    model.Text("BranchLayer"),
                    createLayerChoice,
                    StringComparison.OrdinalIgnoreCase)
                    ? model.Text("NewBranchLayer")
                    : model.Text("BranchLayer");
            productionSettings.BranchLabelLayer =
                NormalizeBranchLayerName(requestedBranchLayer);
            productionSettings.Write(database);

            List<ObjectId> networkIds;
            int unsupported = 0;
            if (selectManually)
            {
                PromptSelectionResult selection =
                    editor.SelectImplied();
                if (selection.Status != PromptStatus.OK ||
                    selection.Value == null ||
                    selection.Value.Count == 0)
                {
                    selection =
                        editor.GetSelection(
                            new PromptSelectionOptions
                            {
                                MessageForAdding =
                                    "\nSelect multiple sewer pipes / structures whose Branch names must be added: ",
                                AllowDuplicates = false,
                                RejectObjectsFromNonCurrentSpace = true
                            });
                }

                if (selection.Status != PromptStatus.OK ||
                    selection.Value == null ||
                    selection.Value.Count == 0)
                    return;

                ReadSelectedNetworks(
                    database,
                    selection.Value.GetObjectIds(),
                    out networkIds,
                    out unsupported);
            }
            else
            {
                networkIds =
                    ReadAllSequencedSewerNetworks(
                        database,
                        civilDocument);
            }

            if (networkIds == null ||
                networkIds.Count == 0)
            {
                editor.WriteMessage(
                    "\nCE_SEWBRANCHNAMES: no CE-sequenced sewer branches were found.");
                return;
            }

            var plans =
                new List<NetworkAlignmentPlan>();
            try
            {
                using (Transaction read =
                    database.TransactionManager.StartTransaction())
                {
                    foreach (ObjectId networkId in
                        networkIds
                            .Distinct()
                            .OrderBy(id =>
                                id.Handle.Value))
                    {
                        plans.Add(
                            BuildNetworkPlan(
                                networkId,
                                read));
                    }
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWBRANCHNAMES cancelled while reading branch geometry. " +
                    exception.Message);
                return;
            }

            int labelsCreated = 0;
            int branchesLabelled = 0;
            try
            {
                using (DocumentLock documentLock =
                    document.LockDocument())
                using (Transaction transaction =
                    database.TransactionManager.StartTransaction())
                {
                    EnsureRegApp(
                        database,
                        transaction);
                    ObjectId layerId =
                        GetOrCreateLayer(
                            database,
                            transaction,
                            productionSettings.BranchLabelLayer);

                    BlockTable blockTable =
                        (BlockTable)transaction.GetObject(
                            database.BlockTableId,
                            OpenMode.ForRead,
                            false);
                    BlockTableRecord modelSpace =
                        (BlockTableRecord)transaction.GetObject(
                            blockTable[BlockTableRecord.ModelSpace],
                            OpenMode.ForWrite,
                            false);

                    foreach (NetworkAlignmentPlan plan in plans)
                    {
                        string networkHandle =
                            plan.NetworkId.Handle.ToString();
                        foreach (BranchAlignmentPlan branchPlan in
                            plan.Branches)
                        {
                            string branchKey =
                                BuildBranchKey(
                                    networkHandle,
                                    branchPlan.BranchName);

                            RemoveExistingGeneratedLabels(
                                modelSpace,
                                branchKey,
                                transaction);

                            IReadOnlyList<SewerBranchLabelPlacement.Placement> placements =
                                SewerBranchLabelPlacement.BuildPlacements(
                                    branchPlan.PlanPoints,
                                    productionSettings.BranchLabelLongSectionLength,
                                    productionSettings.BranchLabelLongSectionFrequency);
                            Dictionary<ObjectId, Point3d> pipeLabelAnchors =
                                ReadPipePlanLabelAnchors(
                                    modelSpace,
                                    branchPlan.PipeIds,
                                    transaction);

                            bool placeAbove =
                                string.Equals(
                                    productionSettings.BranchLabelSide,
                                    "Above",
                                    StringComparison.OrdinalIgnoreCase) ||
                                (!string.Equals(
                                    productionSettings.BranchLabelSide,
                                    "Below",
                                    StringComparison.OrdinalIgnoreCase) &&
                                 (branchPlan.BranchNumber % 2) != 0);

                            foreach (SewerBranchLabelPlacement.Placement placement in
                                placements)
                            {
                                var label =
                                    new MText();
                                label.SetDatabaseDefaults(
                                    database);
                                label.LayerId =
                                    layerId;
                                SewerBranchLabelPlacement.Placement anchoredPlacement =
                                    AnchorToNearestPipePlanLabel(
                                        placement,
                                        pipeLabelAnchors.Values);
                                SewerBranchLabelPlacement.ConfigureLabel(
                                    label,
                                    database,
                                    anchoredPlacement,
                                    branchPlan.BranchName,
                                    productionSettings.LabelHeight,
                                    productionSettings.BranchLabelAboveOffset,
                                    productionSettings.BranchLabelBelowOffset,
                                    placeAbove);
                                label.XData =
                                    BuildTag(
                                        branchKey,
                                        "Label");
                                modelSpace.AppendEntity(
                                    label);
                                transaction.AddNewlyCreatedDBObject(
                                    label,
                                    true);
                                labelsCreated++;
                            }

                            if (placements.Count > 0)
                                branchesLabelled++;
                        }
                    }

                    transaction.Commit();
                }
            }
            catch (System.Exception exception)
            {
                editor.WriteMessage(
                    "\nCE_SEWBRANCHNAMES cancelled. No partial label transaction was committed. " +
                    exception.Message);
                return;
            }

            document.Editor.SetImpliedSelection(
                new ObjectId[0]);
            document.Editor.Regen();
            editor.WriteMessage(
                "\nCE_SEWBRANCHNAMES complete. Branches labelled={0}; green Branch-x labels={1}; unsupported selected objects ignored={2}.",
                branchesLabelled,
                labelsCreated,
                unsupported);
        }

        private static ObjectId ResolveExistingBranchAlignmentId(
            CivilDocument civilDocument,
            NetworkAlignmentPlan plan,
            BranchAlignmentPlan branch,
            Transaction transaction)
        {
            string branchKey = BuildBranchKey(
                plan.NetworkId.Handle.ToString(),
                branch.BranchName);

            foreach (ObjectId alignmentId in civilDocument.GetAlignmentIds())
            {
                CivilAlignment alignment = null;
                try
                {
                    alignment = transaction.GetObject(
                        alignmentId,
                        OpenMode.ForRead,
                        false) as CivilAlignment;
                }
                catch { }
                if (alignment != null &&
                    HasTag(
                        alignment,
                        branchKey,
                        "Alignment"))
                    return alignmentId;
            }

            var referenced = new Dictionary<ObjectId, int>();
            foreach (ObjectId pipeId in branch.PipeIds)
            {
                CivilPipe pipe = null;
                try
                {
                    pipe = transaction.GetObject(
                        pipeId,
                        OpenMode.ForRead,
                        false) as CivilPipe;
                }
                catch { }
                if (pipe == null ||
                    pipe.RefAlignmentId.IsNull ||
                    pipe.RefAlignmentId.IsErased)
                    continue;

                int count;
                referenced.TryGetValue(
                    pipe.RefAlignmentId,
                    out count);
                referenced[pipe.RefAlignmentId] = count + 1;
            }

            foreach (KeyValuePair<ObjectId, int> item in referenced
                .OrderByDescending(pair => pair.Value)
                .ThenBy(pair => pair.Key.Handle.Value))
            {
                CivilAlignment alignment = null;
                try
                {
                    alignment = transaction.GetObject(
                        item.Key,
                        OpenMode.ForRead,
                        false) as CivilAlignment;
                }
                catch { }
                if (alignment != null)
                    return item.Key;
            }

            string exactBranchName = branch.BranchName;
            string networkBranchName =
                (plan.NetworkName ?? string.Empty).Trim() +
                " - " +
                branch.BranchName;
            foreach (ObjectId alignmentId in civilDocument.GetAlignmentIds())
            {
                CivilAlignment alignment = null;
                try
                {
                    alignment = transaction.GetObject(
                        alignmentId,
                        OpenMode.ForRead,
                        false) as CivilAlignment;
                }
                catch { }
                if (alignment == null)
                    continue;

                if (string.Equals(
                        alignment.Name,
                        exactBranchName,
                        StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(
                        alignment.Name,
                        networkBranchName,
                        StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(
                        alignment.Description,
                        "CE sewer alignment - " + branch.BranchName,
                        StringComparison.OrdinalIgnoreCase))
                    return alignmentId;
            }

            return ObjectId.Null;
        }

        private static List<ObjectId> ReadAllSequencedSewerNetworks(
            Database database,
            CivilDocument civilDocument)
        {
            var result = new List<ObjectId>();
            if (database == null || civilDocument == null)
                return result;

            IEnumerable networkIds = null;
            try
            {
                MethodInfo method = civilDocument.GetType().GetMethod(
                    "GetPipeNetworkIds",
                    BindingFlags.Public | BindingFlags.Instance,
                    null,
                    Type.EmptyTypes,
                    null);
                networkIds = method == null
                    ? null
                    : method.Invoke(civilDocument, null) as IEnumerable;
            }
            catch { }

            if (networkIds == null)
                return result;

            using (Transaction transaction =
                database.TransactionManager.StartTransaction())
            {
                foreach (object rawId in networkIds)
                {
                    if (!(rawId is ObjectId))
                        continue;
                    ObjectId networkId = (ObjectId)rawId;
                    CivilNetwork network = transaction.GetObject(
                        networkId,
                        OpenMode.ForRead,
                        false) as CivilNetwork;
                    if (network == null || network.IsReferenceObject)
                        continue;

                    bool hasSequencedPipe = false;
                    foreach (ObjectId pipeId in network.GetPipeIds())
                    {
                        CivilPipe pipe = transaction.GetObject(
                            pipeId,
                            OpenMode.ForRead,
                            false) as CivilPipe;
                        if (pipe != null &&
                            PipeNamePattern.IsMatch(
                                pipe.Name ?? string.Empty))
                        {
                            hasSequencedPipe = true;
                            break;
                        }
                    }

                    if (hasSequencedPipe)
                        result.Add(networkId);
                }
            }

            return result
                .Distinct()
                .OrderBy(id => id.Handle.Value)
                .ToList();
        }

        private static void ReadSelectedNetworks(
            Database database,
            IEnumerable<ObjectId> selectedIds,
            out List<ObjectId> networkIds,
            out int unsupported)
        {
            var ids = new HashSet<ObjectId>();
            unsupported = 0;

            using (Transaction transaction =
                database.TransactionManager.StartTransaction())
            {
                foreach (ObjectId selectedId in selectedIds)
                {
                    DBObject selected = transaction.GetObject(
                        selectedId,
                        OpenMode.ForRead,
                        false);

                    var pipe = selected as CivilPipe;
                    if (pipe != null && !pipe.NetworkId.IsNull)
                    {
                        ids.Add(pipe.NetworkId);
                        continue;
                    }

                    var structure = selected as CivilStructure;
                    if (structure != null && !structure.NetworkId.IsNull)
                    {
                        ids.Add(structure.NetworkId);
                        continue;
                    }

                    unsupported++;
                }
            }

            networkIds = ids.ToList();
        }

        private static NetworkAlignmentPlan BuildNetworkPlan(
            ObjectId networkId,
            Transaction transaction)
        {
            var network = transaction.GetObject(
                networkId,
                OpenMode.ForRead,
                false) as CivilNetwork;
            if (network == null)
            {
                throw new InvalidOperationException(
                    "A selected part does not resolve to a gravity pipe network.");
            }

            if (network.IsReferenceObject)
            {
                throw new InvalidOperationException(
                    "Referenced network '" + network.Name +
                    "' cannot receive local branch alignments.");
            }

            var groupedPipes = new Dictionary<int, List<BranchPipeRecord>>();
            foreach (ObjectId pipeId in network.GetPipeIds())
            {
                var pipe = transaction.GetObject(
                    pipeId,
                    OpenMode.ForRead,
                    false) as CivilPipe;
                if (pipe == null)
                {
                    continue;
                }

                int branchNumber;
                int sequenceNumber;
                if (!TryReadBranch(pipe, out branchNumber, out sequenceNumber))
                {
                    continue;
                }

                if (pipe.StartStructureId.IsNull || pipe.EndStructureId.IsNull)
                {
                    throw new InvalidOperationException(
                        "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                        " contains an unconnected pipe.");
                }

                List<BranchPipeRecord> records;
                if (!groupedPipes.TryGetValue(branchNumber, out records))
                {
                    records = new List<BranchPipeRecord>();
                    groupedPipes[branchNumber] = records;
                }

                records.Add(new BranchPipeRecord(
                    pipeId,
                    pipe.StartStructureId,
                    pipe.EndStructureId,
                    sequenceNumber));
            }

            if (groupedPipes.Count == 0)
            {
                throw new InvalidOperationException(
                    "Network '" + network.Name +
                    "' contains no CE-sequenced branch pipes. Run CE_SEWSEQ first.");
            }

            var branches = new List<BranchAlignmentPlan>();
            foreach (KeyValuePair<int, List<BranchPipeRecord>> pair in
                groupedPipes.OrderBy(item => item.Key))
            {
                branches.Add(BuildBranchPlan(
                    networkId,
                    pair.Key,
                    pair.Value,
                    transaction));
            }

            return new NetworkAlignmentPlan(
                networkId,
                network.Name,
                branches);
        }

        private static bool TryReadBranch(
            CivilPipe pipe,
            out int branchNumber,
            out int sequenceNumber)
        {
            branchNumber = 0;
            sequenceNumber = int.MaxValue;

            Match pipeMatch = PipeNamePattern.Match(pipe.Name ?? string.Empty);
            if (pipeMatch.Success)
            {
                return int.TryParse(
                           pipeMatch.Groups["branch"].Value,
                           NumberStyles.None,
                           CultureInfo.InvariantCulture,
                           out branchNumber) &&
                       int.TryParse(
                           pipeMatch.Groups["sequence"].Value,
                           NumberStyles.None,
                           CultureInfo.InvariantCulture,
                           out sequenceNumber);
            }

            Match branchMatch = BranchNamePattern.Match(
                pipe.Description ?? string.Empty);
            if (!branchMatch.Success ||
                !int.TryParse(
                    branchMatch.Groups["branch"].Value,
                    NumberStyles.None,
                    CultureInfo.InvariantCulture,
                    out branchNumber))
            {
                return false;
            }

            return true;
        }

        private static BranchAlignmentPlan BuildBranchPlan(
            ObjectId networkId,
            int branchNumber,
            IReadOnlyList<BranchPipeRecord> pipeRecords,
            Transaction transaction)
        {
            var adjacency = new Dictionary<ObjectId, List<BranchPipeRecord>>();
            foreach (BranchPipeRecord pipe in pipeRecords)
            {
                AddPipe(adjacency, pipe.StartStructureId, pipe);
                AddPipe(adjacency, pipe.EndStructureId, pipe);
            }

            if (adjacency.Any(item => item.Value.Count > 2))
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " is not a single continuous path.");
            }

            List<ObjectId> endpoints = adjacency
                .Where(item => item.Value.Count == 1)
                .Select(item => item.Key)
                .ToList();
            if (endpoints.Count != 2)
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " must have exactly two endpoints.");
            }

            ObjectId startId = ResolveSequencedBranchStart(
                branchNumber,
                endpoints,
                pipeRecords,
                transaction);

            string startStructureName = ReadStructureName(
                startId,
                transaction);

            var unusedPipes = new HashSet<ObjectId>(
                pipeRecords.Select(record => record.PipeId));
            var orderedStructures = new List<ObjectId>();
            var orderedPipes = new List<ObjectId>();
            ObjectId current = startId;

            while (true)
            {
                orderedStructures.Add(current);
                BranchPipeRecord next = adjacency[current]
                    .Where(record => unusedPipes.Contains(record.PipeId))
                    .OrderBy(record => record.SequenceNumber)
                    .ThenBy(record => record.PipeId.Handle.Value)
                    .FirstOrDefault();
                if (next == null)
                {
                    break;
                }

                unusedPipes.Remove(next.PipeId);
                orderedPipes.Add(next.PipeId);
                current = next.Other(current);
            }

            if (unusedPipes.Count != 0 ||
                orderedPipes.Count != pipeRecords.Count ||
                orderedStructures.Count != orderedPipes.Count + 1)
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " contains disconnected or ambiguous pipe geometry.");
            }

            List<Point3d> planPoints = BuildPlanPoints(
                orderedStructures,
                orderedPipes,
                transaction);
            if (planPoints.Count < 2)
            {
                throw new InvalidOperationException(
                    "Branch-" + branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " does not contain enough plan geometry for an alignment.");
            }

            return new BranchAlignmentPlan(
                networkId,
                branchNumber,
                startStructureName,
                orderedStructures,
                orderedPipes,
                planPoints);
        }

        private static ObjectId ResolveSequencedBranchStart(
            int branchNumber,
            IList<ObjectId> endpoints,
            IReadOnlyList<BranchPipeRecord> pipeRecords,
            Transaction transaction)
        {
            if (endpoints == null || endpoints.Count != 2)
                throw new InvalidOperationException(
                    "Branch-" +
                    branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " does not expose exactly two branch endpoints.");

            // The branch-start structure is defined by pipe sequence, not by
            // assuming that every branch begins at MH{branch}.1. Side branches
            // commonly begin on a shared main-branch structure such as MH1.2,
            // MH1.3, etc. P#.1 is therefore authoritative: the endpoint touched
            // by P#.1 but not by the next pipe in the same branch is the start.
            BranchPipeRecord firstPipe = pipeRecords
                .OrderBy(record => record.SequenceNumber)
                .ThenBy(record => record.PipeId.Handle.Value)
                .FirstOrDefault();
            if (firstPipe == null)
                throw new InvalidOperationException(
                    "Branch-" +
                    branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " contains no sequenced pipe.");

            if (firstPipe.SequenceNumber != 1)
            {
                throw new InvalidOperationException(
                    "Branch-" +
                    branchNumber.ToString(CultureInfo.InvariantCulture) +
                    " does not contain P" +
                    branchNumber.ToString(CultureInfo.InvariantCulture) +
                    ".1 as its first sequenced pipe. Run CE_SEWSEQ before rebuilding sewer alignments.");
            }

            List<ObjectId> firstPipeEndpoints = endpoints
                .Where(id =>
                    id == firstPipe.StartStructureId ||
                    id == firstPipe.EndStructureId)
                .Distinct()
                .ToList();

            if (firstPipeEndpoints.Count == 1)
                return firstPipeEndpoints[0];

            // One-pipe/very short branches expose both ends as branch
            // endpoints. CE_SEWSEQ numbers the newly owned/free end as
            // MH{branch}.1 and keeps the shared downstream junction under the
            // earlier branch number. Therefore the current branch's own MH#.1
            // is authoritative; choosing the shared earlier-branch structure
            // reverses short alignments.
            List<ObjectId> currentBranchCandidates = endpoints
                .Select(id => new
                {
                    Id = id,
                    Key = ReadStructureSortKey(id, transaction)
                })
                .Where(item =>
                    item.Key.HasValue &&
                    item.Key.Value.Branch == branchNumber)
                .OrderBy(item => item.Key.Value.Sequence)
                .ThenBy(item => item.Id.Handle.Value)
                .Select(item => item.Id)
                .ToList();

            ObjectId exactBranchStart = currentBranchCandidates
                .FirstOrDefault(id =>
                {
                    StructureSortKey? key =
                        ReadStructureSortKey(id, transaction);
                    return key.HasValue &&
                        key.Value.Sequence == 1;
                });
            if (!exactBranchStart.IsNull)
                return exactBranchStart;

            if (currentBranchCandidates.Count == 1)
                return currentBranchCandidates[0];

            // If the current-branch name is unavailable (legacy/manual naming),
            // prefer the P#.1 flow-upstream endpoint before falling back to
            // deterministic structure naming. This keeps repaired short branches
            // aligned with the gravity-network pipe direction.
            CivilPipe firstPipeEntity = null;
            try
            {
                firstPipeEntity = transaction.GetObject(
                    firstPipe.PipeId,
                    OpenMode.ForRead,
                    false) as CivilPipe;
            }
            catch { }
            if (firstPipeEntity != null)
            {
                bool forward;
                if (SewerPipeConnections.TryForward(
                        firstPipeEntity,
                        transaction,
                        out forward))
                {
                    ObjectId flowStart = forward
                        ? firstPipeEntity.StartStructureId
                        : firstPipeEntity.EndStructureId;
                    if (endpoints.Contains(flowStart))
                        return flowStart;
                }
            }

            // Last named fallback: use the numerically first endpoint only when
            // no current-branch MH#.1 and no usable P#.1 flow direction exists.
            ObjectId namedStart = endpoints
                .Select(id => new
                {
                    Id = id,
                    Key = ReadStructureSortKey(id, transaction)
                })
                .Where(item => item.Key.HasValue)
                .OrderBy(item => item.Key.Value.Branch)
                .ThenBy(item => item.Key.Value.Sequence)
                .Select(item => item.Id)
                .FirstOrDefault();
            if (!namedStart.IsNull)
                return namedStart;

            // Final deterministic fallback: use the first-pipe endpoint with the
            // lowest handle. Do not derive branch direction from rim elevation;
            // alignment chainage must follow the CE pipe/structure sequence.
            if (firstPipeEndpoints.Count > 0)
                return firstPipeEndpoints
                    .OrderBy(id => id.Handle.Value)
                    .First();

            return endpoints
                .OrderBy(id => id.Handle.Value)
                .First();
        }

        private static string ReadStructureName(
            ObjectId structureId,
            Transaction transaction)
        {
            try
            {
                CivilStructure structure = transaction.GetObject(
                    structureId,
                    OpenMode.ForRead,
                    false) as CivilStructure;
                return structure == null ||
                    string.IsNullOrWhiteSpace(structure.Name)
                    ? structureId.Handle.ToString()
                    : structure.Name;
            }
            catch
            {
                return structureId.Handle.ToString();
            }
        }

        private static StructureSortKey? ReadStructureSortKey(
            ObjectId structureId,
            Transaction transaction)
        {
            try
            {
                CivilStructure structure = transaction.GetObject(
                    structureId,
                    OpenMode.ForRead,
                    false) as CivilStructure;
                Match match = StructureNamePattern.Match(
                    structure == null
                        ? string.Empty
                        : structure.Name ?? string.Empty);
                if (!match.Success)
                    return null;

                int branch;
                int sequence;
                if (!int.TryParse(
                        match.Groups["branch"].Value,
                        NumberStyles.None,
                        CultureInfo.InvariantCulture,
                        out branch) ||
                    !int.TryParse(
                        match.Groups["sequence"].Value,
                        NumberStyles.None,
                        CultureInfo.InvariantCulture,
                        out sequence))
                    return null;

                return new StructureSortKey(
                    branch,
                    sequence);
            }
            catch
            {
                return null;
            }
        }

        private static void AddPipe(
            IDictionary<ObjectId, List<BranchPipeRecord>> adjacency,
            ObjectId structureId,
            BranchPipeRecord pipe)
        {
            List<BranchPipeRecord> list;
            if (!adjacency.TryGetValue(structureId, out list))
            {
                list = new List<BranchPipeRecord>();
                adjacency[structureId] = list;
            }

            list.Add(pipe);
        }

        private static double GetRimElevation(
            ObjectId structureId,
            Transaction transaction)
        {
            var structure = transaction.GetObject(
                structureId,
                OpenMode.ForRead,
                false) as CivilStructure;
            if (structure == null)
            {
                return double.MinValue;
            }

            double rim = structure.RimElevation;
            return double.IsNaN(rim) || double.IsInfinity(rim)
                ? structure.Position.Z
                : rim;
        }

        private static List<Point3d> BuildPlanPoints(
            IReadOnlyList<ObjectId> structureIds,
            IReadOnlyList<ObjectId> pipeIds,
            Transaction transaction)
        {
            var points = new List<Point3d>();

            for (int index = 0; index < pipeIds.Count; index++)
            {
                var pipe = transaction.GetObject(
                    pipeIds[index],
                    OpenMode.ForRead,
                    false) as CivilPipe;
                if (pipe == null)
                {
                    continue;
                }

                ObjectId fromStructureId = structureIds[index];
                bool forward = pipe.StartStructureId == fromStructureId;
                int segmentCount = IsCurvedPipe(pipe)
                    ? CurvedPipeSegments
                    : 1;

                for (int segment = 0; segment <= segmentCount; segment++)
                {
                    double fraction = segment / (double)segmentCount;
                    double parameter = forward ? fraction : 1.0 - fraction;
                    Point3d point = pipe.GetPointAtParam(parameter);
                    AddDistinctPlanPoint(points, point);
                }
            }

            // Anchor the branch geometry to the actual sequenced
            // structure centres. Pipe endpoint geometry can be slightly offset
            // from structure insertion points in some Civil 3D networks; using
            // The resolved branch-start structure explicitly guarantees station
            // 0.000 is at the true P#.1 start (including shared structures such
            // as MH1.2/MH1.3), not at a nearby inherited pipe endpoint.
            if (points.Count > 0 && structureIds.Count > 0)
            {
                CivilStructure firstStructure = transaction.GetObject(
                    structureIds[0],
                    OpenMode.ForRead,
                    false) as CivilStructure;
                if (firstStructure != null)
                {
                    Point3d first = firstStructure.Position;
                    points[0] = new Point3d(
                        first.X,
                        first.Y,
                        points[0].Z);
                }

                CivilStructure lastStructure = transaction.GetObject(
                    structureIds[structureIds.Count - 1],
                    OpenMode.ForRead,
                    false) as CivilStructure;
                if (lastStructure != null)
                {
                    Point3d last = lastStructure.Position;
                    points[points.Count - 1] = new Point3d(
                        last.X,
                        last.Y,
                        points[points.Count - 1].Z);
                }
            }

            return points;
        }

        private static bool IsCurvedPipe(CivilPipe pipe)
        {
            try
            {
                return pipe.Curve2d != null;
            }
            catch (InvalidOperationException)
            {
                return false;
            }
        }

        private static void AddDistinctPlanPoint(
            ICollection<Point3d> points,
            Point3d point)
        {
            Point3d planPoint = new Point3d(point.X, point.Y, 0.0);
            Point3d last = points.Count == 0
                ? Point3d.Origin
                : points.Last();

            if (points.Count == 0 || last.DistanceTo(planPoint) > GeometryTolerance)
            {
                points.Add(planPoint);
            }
        }

        private static void CreateAlignmentsAndLabels(
            Database database,
            CivilDocument civilDocument,
            IReadOnlyList<NetworkAlignmentPlan> plans,
            out int alignmentsCreated,
            out int labelsCreated)
        {
            alignmentsCreated = 0;
            labelsCreated = 0;
            SewerProductionSettings productionSettings =
                SewerProductionSettings.Read(database);

            using (Transaction transaction =
                database.TransactionManager.StartTransaction())
            {
                EnsureRegApp(database, transaction);
                ObjectId layerId = GetOrCreateLayer(database, transaction);
                ObjectId branchLabelLayerId = GetOrCreateLayer(
                    database,
                    transaction,
                    productionSettings.BranchLabelLayer);
                string alignmentStyleName;
                ObjectId alignmentStyleId = CivilStyleCatalogV2.ResolveStyleId(
                    database,
                    civilDocument,
                    "Alignment Style",
                    productionSettings.AlignmentStyle,
                    transaction,
                    out alignmentStyleName);
                string labelSetStyleName;
                ObjectId labelSetStyleId = CivilStyleCatalogV2.ResolveStyleId(
                    database,
                    civilDocument,
                    "Alignment Label Set Style",
                    productionSettings.AlignmentLabelSetStyle,
                    transaction,
                    out labelSetStyleName);

                BlockTable blockTable = (BlockTable)transaction.GetObject(
                    database.BlockTableId,
                    OpenMode.ForRead,
                    false);
                BlockTableRecord modelSpace = (BlockTableRecord)transaction.GetObject(
                    blockTable[BlockTableRecord.ModelSpace],
                    OpenMode.ForWrite,
                    false);

                var reservedNames = new HashSet<string>(
                    StringComparer.OrdinalIgnoreCase);

                foreach (NetworkAlignmentPlan plan in plans)
                {
                    string networkHandle = plan.NetworkId.Handle.ToString();
                    foreach (BranchAlignmentPlan branch in plan.Branches)
                    {
                        string branchKey = BuildBranchKey(
                            networkHandle,
                            branch.BranchName);

                        RemoveExistingGeneratedObjects(
                            civilDocument,
                            modelSpace,
                            branchKey,
                            transaction);

                        string alignmentName = ResolveAlignmentName(
                            civilDocument,
                            plan.NetworkName,
                            branch.BranchName,
                            reservedNames,
                            transaction);

                        ObjectId polylineId = AddSourcePolyline(
                            database,
                            modelSpace,
                            branch.PlanPoints,
                            layerId,
                            transaction);

                        var polylineOptions = new CivilPolylineOptions
                        {
                            AddCurvesBetweenTangents = false,
                            EraseExistingEntities = true,
                            PlineId = polylineId
                        };

                        ObjectId alignmentId = CivilAlignment.Create(
                            civilDocument,
                            polylineOptions,
                            alignmentName,
                            ObjectId.Null,
                            layerId,
                            alignmentStyleId,
                            labelSetStyleId);

                        var alignment = transaction.GetObject(
                            alignmentId,
                            OpenMode.ForWrite,
                            false) as CivilAlignment;
                        if (alignment == null)
                        {
                            throw new InvalidOperationException(
                                "Civil 3D did not return the created sewer branch alignment.");
                        }

                        EnsureAlignmentDirectionAtBranchStart(
                            alignment,
                            branch.BranchName,
                            branch.StartStructureName,
                            branch.PlanPoints[0]);

                        ForceAlignmentStartStationZero(
                            alignment,
                            branch.BranchName,
                            branch.StartStructureName,
                            branch.PlanPoints[0]);

                        alignment.Description =
                            "CE sewer alignment - " + branch.BranchName;
                        alignment.XData = BuildTag(branchKey, "Alignment");
                        SewerPartAlignmentBinding.BindBranch(transaction, branch.PipeIds, branch.StructureIds, alignmentId);
                        alignmentsCreated++;

                        IReadOnlyList<SewerBranchLabelPlacement.Placement> placements =
                            SewerBranchLabelPlacement.BuildPlacements(
                                branch.PlanPoints,
                                productionSettings.BranchLabelLongSectionLength,
                                productionSettings.BranchLabelLongSectionFrequency);
                        Dictionary<ObjectId, Point3d> pipeLabelAnchors =
                            ReadPipePlanLabelAnchors(
                                modelSpace,
                                branch.PipeIds,
                                transaction);
                        double paperHeight = productionSettings.LabelHeight;
                        bool placeAbove = string.Equals(
                                productionSettings.BranchLabelSide,
                                "Above",
                                StringComparison.OrdinalIgnoreCase) ||
                            (!string.Equals(
                                productionSettings.BranchLabelSide,
                                "Below",
                                StringComparison.OrdinalIgnoreCase) &&
                             (branch.BranchNumber % 2) != 0);

                        foreach (SewerBranchLabelPlacement.Placement placement in placements)
                        {
                            var label = new MText();
                            label.SetDatabaseDefaults(database);
                            label.LayerId = branchLabelLayerId;
                            SewerBranchLabelPlacement.Placement anchoredPlacement =
                                AnchorToNearestPipePlanLabel(
                                    placement,
                                    pipeLabelAnchors.Values);
                            SewerBranchLabelPlacement.ConfigureLabel(
                                label,
                                database,
                                anchoredPlacement,
                                branch.BranchName,
                                paperHeight,
                                productionSettings.BranchLabelAboveOffset,
                                productionSettings.BranchLabelBelowOffset,
                                placeAbove);
                            label.XData = BuildTag(branchKey, "Label");
                            modelSpace.AppendEntity(label);
                            transaction.AddNewlyCreatedDBObject(label, true);
                            labelsCreated++;
                        }
                    }
                }

                transaction.Commit();
            }
        }

        private static void EnsureAlignmentDirectionAtBranchStart(
            CivilAlignment alignment,
            string branchName,
            string startStructureName,
            Point3d sequencedStartPoint)
        {
            if (alignment == null)
                throw new ArgumentNullException("alignment");

            Point2d expected = new Point2d(
                sequencedStartPoint.X,
                sequencedStartPoint.Y);
            Point2d start = ReadAlignmentStartPoint(alignment);
            Point2d end = ReadAlignmentEndPoint(alignment);

            double startDistance = PlanDistance(start, expected);
            double endDistance = PlanDistance(end, expected);
            if (startDistance <= endDistance + 0.001)
                return;

            MethodInfo reverse = alignment.GetType().GetMethod(
                "Reverse",
                BindingFlags.Public | BindingFlags.Instance,
                null,
                Type.EmptyTypes,
                null);
            if (reverse == null)
                throw new InvalidOperationException(
                    (branchName ?? "Sewer branch") +
                    " was created opposite to start structure " +
                    (string.IsNullOrWhiteSpace(startStructureName) ? "<unknown>" : startStructureName) +
                    ", but Civil 3D did not expose Alignment.Reverse().");

            reverse.Invoke(alignment, null);

            start = ReadAlignmentStartPoint(alignment);
            end = ReadAlignmentEndPoint(alignment);
            startDistance = PlanDistance(start, expected);
            endDistance = PlanDistance(end, expected);
            if (startDistance > endDistance + 0.001)
                throw new InvalidOperationException(
                    (branchName ?? "Sewer branch") +
                    " could not be reversed to start at " +
                    (string.IsNullOrWhiteSpace(startStructureName) ? "the resolved branch-start structure" : startStructureName) +
                    ".");
        }

        private static Point2d ReadAlignmentEndPoint(
            CivilAlignment alignment)
        {
            if (alignment == null)
                return new Point2d(double.NaN, double.NaN);

            try
            {
                double station = ReadDoubleProperty(
                    alignment,
                    "EndingStation",
                    double.NaN);
                if (double.IsNaN(station) ||
                    double.IsInfinity(station))
                    return new Point2d(double.NaN, double.NaN);

                double x = 0.0;
                double y = 0.0;
                alignment.PointLocation(
                    station,
                    0.0,
                    ref x,
                    ref y);
                return new Point2d(x, y);
            }
            catch
            {
                return new Point2d(double.NaN, double.NaN);
            }
        }

        private static double PlanDistance(
            Point2d first,
            Point2d second)
        {
            if (double.IsNaN(first.X) ||
                double.IsNaN(first.Y) ||
                double.IsNaN(second.X) ||
                double.IsNaN(second.Y))
                return double.PositiveInfinity;

            double dx = first.X - second.X;
            double dy = first.Y - second.Y;
            return Math.Sqrt((dx * dx) + (dy * dy));
        }

        private static void ForceAlignmentStartStationZero(
            CivilAlignment alignment,
            string branchName,
            string startStructureName,
            Point3d sequencedStartPoint)
        {
            if (alignment == null)
                throw new ArgumentNullException("alignment");

            const double tolerance = 0.001;
            Point2d startPoint = new Point2d(
                sequencedStartPoint.X,
                sequencedStartPoint.Y);

            // Sewer branch alignments must use continuous chainage from their
            // resolved start structure. Old/manual alignments can carry station
            // equations such as 40+40 / 40+52 even after their geometry is
            // reversed. Remove those equations first, then anchor the reference
            // point itself at 0+000.
            try
            {
                while (alignment.StationEquations.Count > 0)
                    alignment.StationEquations.Remove(
                        alignment.StationEquations.Count - 1);
            }
            catch (System.Exception exception)
            {
                throw new InvalidOperationException(
                    (branchName ?? "Sewer branch") +
                    " could not clear inherited station equations before resetting " +
                    (string.IsNullOrWhiteSpace(startStructureName)
                        ? "the branch start"
                        : startStructureName) +
                    " to 0+000. " +
                    exception.Message,
                    exception);
            }

            try
            {
                alignment.ReferencePoint = startPoint;
                alignment.ReferencePointStation = 0.0;
            }
            catch (System.Exception exception)
            {
                throw new InvalidOperationException(
                    (branchName ?? "Sewer branch") +
                    " could not assign station 0+000 to start structure " +
                    (string.IsNullOrWhiteSpace(startStructureName)
                        ? "<unknown>"
                        : startStructureName) +
                    ". " +
                    exception.Message,
                    exception);
            }

            double station = double.NaN;
            double offset = double.NaN;
            try
            {
                alignment.StationOffset(
                    startPoint.X,
                    startPoint.Y,
                    ref station,
                    ref offset);
            }
            catch { }

            if (double.IsNaN(station) ||
                double.IsInfinity(station) ||
                Math.Abs(station) > tolerance ||
                double.IsNaN(offset) ||
                double.IsInfinity(offset) ||
                Math.Abs(offset) > tolerance)
            {
                throw new InvalidOperationException(
                    (branchName ?? "Sewer branch") +
                    " alignment failed its final start-chainage verification. " +
                    (string.IsNullOrWhiteSpace(startStructureName)
                        ? "Resolved branch start"
                        : startStructureName) +
                    " reports station " +
                    (double.IsNaN(station)
                        ? "<unavailable>"
                        : station.ToString(
                            "0.###",
                            CultureInfo.InvariantCulture)) +
                    " instead of 0+000.");
            }
        }

        private static Point2d ReadAlignmentStartPoint(
            CivilAlignment alignment)
        {
            if (alignment == null)
                return new Point2d(double.NaN, double.NaN);

            try
            {
                double x = 0.0;
                double y = 0.0;
                alignment.PointLocation(
                    alignment.StartingStation,
                    0.0,
                    ref x,
                    ref y);
                return new Point2d(x, y);
            }
            catch
            {
                return new Point2d(double.NaN, double.NaN);
            }
        }

        private static bool TrySetDoubleProperty(
            object target,
            string propertyName,
            double value)
        {
            return TrySetProperty(
                target,
                propertyName,
                value);
        }

        private static bool TrySetProperty(
            object target,
            string propertyName,
            object value)
        {
            if (target == null ||
                string.IsNullOrWhiteSpace(propertyName))
                return false;

            try
            {
                PropertyInfo property = target.GetType().GetProperty(
                    propertyName,
                    BindingFlags.Public | BindingFlags.Instance);
                if (property == null || !property.CanWrite)
                    return false;

                property.SetValue(target, value, null);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static double ReadDoubleProperty(
            object target,
            string propertyName,
            double fallback)
        {
            if (target == null ||
                string.IsNullOrWhiteSpace(propertyName))
                return fallback;

            try
            {
                PropertyInfo property = target.GetType().GetProperty(
                    propertyName,
                    BindingFlags.Public | BindingFlags.Instance);
                if (property == null || !property.CanRead)
                    return fallback;

                object value = property.GetValue(target, null);
                return value == null
                    ? fallback
                    : Convert.ToDouble(
                        value,
                        CultureInfo.InvariantCulture);
            }
            catch
            {
                return fallback;
            }
        }

        private static ObjectId GetFirstStyleId(
            IEnumerable<ObjectId> styleIds,
            string description)
        {
            ObjectId id = styleIds.FirstOrDefault();
            if (id.IsNull)
            {
                throw new InvalidOperationException(
                    "The drawing contains no " + description + ".");
            }

            return id;
        }

        private static ObjectId AddSourcePolyline(
            Database database,
            BlockTableRecord modelSpace,
            IReadOnlyList<Point3d> points,
            ObjectId layerId,
            Transaction transaction)
        {
            var polyline = new Polyline(points.Count);
            polyline.SetDatabaseDefaults(database);
            polyline.LayerId = layerId;

            for (int index = 0; index < points.Count; index++)
            {
                polyline.AddVertexAt(
                    index,
                    new Point2d(points[index].X, points[index].Y),
                    0.0,
                    0.0,
                    0.0);
            }

            modelSpace.AppendEntity(polyline);
            transaction.AddNewlyCreatedDBObject(polyline, true);
            return polyline.ObjectId;
        }

        private static string ResolveAlignmentName(
            CivilDocument civilDocument,
            string networkName,
            string branchName,
            ISet<string> reservedNames,
            Transaction transaction)
        {
            var existing = new HashSet<string>(
                StringComparer.OrdinalIgnoreCase);
            foreach (ObjectId alignmentId in civilDocument.GetAlignmentIds())
            {
                var alignment = transaction.GetObject(
                    alignmentId,
                    OpenMode.ForRead,
                    false) as CivilAlignment;
                if (alignment != null)
                {
                    existing.Add(alignment.Name);
                }
            }

            string preferred = branchName;
            if (!existing.Contains(preferred) && reservedNames.Add(preferred))
            {
                return preferred;
            }

            string baseName = SanitizeName(networkName) + " - " + branchName;
            string candidate = baseName;
            int suffix = 2;
            while (existing.Contains(candidate) || !reservedNames.Add(candidate))
            {
                candidate = baseName + " (" +
                    suffix.ToString(CultureInfo.InvariantCulture) + ")";
                suffix++;
            }

            return candidate;
        }

        private static string SanitizeName(string value)
        {
            string text = string.IsNullOrWhiteSpace(value)
                ? "Sewer Network"
                : value.Trim();
            foreach (char invalid in new[] { '<', '>', '/', '\\', '"', ':', ';', '?', '*', '|', ',', '=' })
            {
                text = text.Replace(invalid, '-');
            }

            return text;
        }

        private static void RemoveExistingGeneratedLabels(
            BlockTableRecord modelSpace,
            string branchKey,
            Transaction transaction)
        {
            if (modelSpace == null ||
                transaction == null)
                return;

            foreach (ObjectId entityId in modelSpace)
            {
                DBObject entity = null;
                try
                {
                    entity =
                        transaction.GetObject(
                            entityId,
                            OpenMode.ForRead,
                            false);
                }
                catch { }

                if (entity == null ||
                    !HasTag(
                        entity,
                        branchKey,
                        "Label"))
                    continue;

                try
                {
                    entity.UpgradeOpen();
                    entity.Erase();
                }
                catch { }
            }
        }

        private static void RemoveExistingGeneratedObjects(
            CivilDocument civilDocument,
            BlockTableRecord modelSpace,
            string branchKey,
            Transaction transaction)
        {
            foreach (ObjectId alignmentId in civilDocument.GetAlignmentIds())
            {
                DBObject alignment = transaction.GetObject(
                    alignmentId,
                    OpenMode.ForRead,
                    false);
                if (HasTag(alignment, branchKey, "Alignment"))
                {
                    alignment.UpgradeOpen();
                    alignment.Erase();
                }
            }

            foreach (ObjectId entityId in modelSpace)
            {
                DBObject entity = transaction.GetObject(
                    entityId,
                    OpenMode.ForRead,
                    false);
                if (HasTag(entity, branchKey, "Label"))
                {
                    entity.UpgradeOpen();
                    entity.Erase();
                }
            }
        }

        private static bool HasTag(
            DBObject databaseObject,
            string branchKey,
            string objectType)
        {
            using (ResultBuffer data =
                databaseObject.GetXDataForApplication(RegAppName))
            {
                if (data == null)
                {
                    return false;
                }

                string[] values = data.AsArray()
                    .Where(value => value.TypeCode ==
                        (int)DxfCode.ExtendedDataAsciiString)
                    .Select(value => value.Value as string)
                    .Where(value => value != null)
                    .ToArray();

                return values.Length >= 2 &&
                       string.Equals(values[0], branchKey, StringComparison.Ordinal) &&
                       string.Equals(values[1], objectType, StringComparison.Ordinal);
            }
        }

        private static ResultBuffer BuildTag(
            string branchKey,
            string objectType)
        {
            return new ResultBuffer(
                new TypedValue(
                    (int)DxfCode.ExtendedDataRegAppName,
                    RegAppName),
                new TypedValue(
                    (int)DxfCode.ExtendedDataAsciiString,
                    branchKey),
                new TypedValue(
                    (int)DxfCode.ExtendedDataAsciiString,
                    objectType));
        }

        private static string BuildBranchKey(
            string networkHandle,
            string branchName)
        {
            return networkHandle + "|" + branchName;
        }

        private static string NormalizeBranchLayerName(string value)
        {
            string name = (value ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(name))
                return "CE-BRANCH-LABELS";
            return name;
        }

        private static List<string> ReadLayerNames(Database database)
        {
            var names = new List<string>();
            if (database == null) return names;
            using (Transaction transaction =
                database.TransactionManager.StartTransaction())
            {
                LayerTable layers = transaction.GetObject(
                    database.LayerTableId,
                    OpenMode.ForRead,
                    false) as LayerTable;
                if (layers == null) return names;
                foreach (ObjectId id in layers)
                {
                    LayerTableRecord layer = transaction.GetObject(
                        id,
                        OpenMode.ForRead,
                        false) as LayerTableRecord;
                    if (layer != null &&
                        !string.IsNullOrWhiteSpace(layer.Name))
                        names.Add(layer.Name);
                }
            }
            return names
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private static Dictionary<ObjectId, Point3d> ReadPipePlanLabelAnchors(
            BlockTableRecord modelSpace,
            IEnumerable<ObjectId> pipeIds,
            Transaction transaction)
        {
            var result = new Dictionary<ObjectId, Point3d>();
            if (modelSpace == null || transaction == null) return result;
            var pipes = new HashSet<ObjectId>(
                (pipeIds ?? Enumerable.Empty<ObjectId>())
                    .Where(id => !id.IsNull && !id.IsErased));

            foreach (ObjectId id in modelSpace)
            {
                Entity entity = null;
                try
                {
                    entity = transaction.GetObject(
                        id,
                        OpenMode.ForRead,
                        false) as Entity;
                }
                catch { }
                if (entity == null) continue;

                string typeName = entity.GetType().Name ?? string.Empty;
                // Structure labels are deliberately excluded. BRANCH names are
                // allowed to key off plan PipeLabel text only.
                if (typeName.IndexOf(
                        "PipeLabel",
                        StringComparison.OrdinalIgnoreCase) < 0 ||
                    typeName.IndexOf(
                        "Structure",
                        StringComparison.OrdinalIgnoreCase) >= 0)
                    continue;

                ObjectId featureId = ReadLabelFeatureId(entity, pipes);
                if (featureId.IsNull || !pipes.Contains(featureId))
                    continue;

                Point3d point;
                if (!TryReadLabelCentre(entity, out point))
                    continue;
                result[featureId] = point;
            }

            return result;
        }

        private static ObjectId ReadLabelFeatureId(
            Entity label,
            ISet<ObjectId> allowedPipeIds)
        {
            if (label == null || allowedPipeIds == null)
                return ObjectId.Null;

            foreach (string propertyName in new[]
            {
                "FeatureId",
                "PipeId",
                "ParentEntityId",
                "SourceEntityId",
                "AnchorId"
            })
            {
                try
                {
                    PropertyInfo property = label.GetType().GetProperty(
                        propertyName,
                        BindingFlags.Public | BindingFlags.Instance);
                    if (property == null ||
                        !property.CanRead ||
                        property.PropertyType != typeof(ObjectId))
                        continue;

                    ObjectId value =
                        (ObjectId)property.GetValue(label, null);
                    if (!value.IsNull && allowedPipeIds.Contains(value))
                        return value;
                }
                catch { }
            }

            return ObjectId.Null;
        }

        private static bool TryReadLabelCentre(
            Entity label,
            out Point3d point)
        {
            point = Point3d.Origin;
            if (label == null) return false;

            try
            {
                Extents3d extents = label.GeometricExtents;
                point = new Point3d(
                    (extents.MinPoint.X + extents.MaxPoint.X) * 0.5,
                    (extents.MinPoint.Y + extents.MaxPoint.Y) * 0.5,
                    (extents.MinPoint.Z + extents.MaxPoint.Z) * 0.5);
                return true;
            }
            catch { }

            foreach (string propertyName in new[]
            {
                "LabelLocation",
                "Location",
                "AnchorLocation"
            })
            {
                try
                {
                    PropertyInfo property = label.GetType().GetProperty(
                        propertyName,
                        BindingFlags.Public | BindingFlags.Instance);
                    if (property == null ||
                        !property.CanRead ||
                        property.PropertyType != typeof(Point3d))
                        continue;
                    point = (Point3d)property.GetValue(label, null);
                    return true;
                }
                catch { }
            }

            return false;
        }

        private static SewerBranchLabelPlacement.Placement
            AnchorToNearestPipePlanLabel(
                SewerBranchLabelPlacement.Placement placement,
                IEnumerable<Point3d> pipeLabelAnchors)
        {
            if (placement == null) return null;
            Point3d best = placement.Point;
            double bestDistance = double.PositiveInfinity;
            bool found = false;

            foreach (Point3d candidate in
                pipeLabelAnchors ?? Enumerable.Empty<Point3d>())
            {
                double dx = candidate.X - placement.Point.X;
                double dy = candidate.Y - placement.Point.Y;
                double distance = dx * dx + dy * dy;
                if (distance >= bestDistance) continue;
                bestDistance = distance;
                best = candidate;
                found = true;
            }

            return found
                ? new SewerBranchLabelPlacement.Placement(
                    best,
                    placement.Rotation)
                : placement;
        }

        private static ObjectId GetOrCreateLayer(
            Database database,
            Transaction transaction)
        {
            LayerTable layers = (LayerTable)transaction.GetObject(
                database.LayerTableId,
                OpenMode.ForRead,
                false);
            if (layers.Has(AlignmentLayerName))
            {
                ObjectId existingId = layers[AlignmentLayerName];
                var existing = transaction.GetObject(
                    existingId,
                    OpenMode.ForRead,
                    false) as LayerTableRecord;
                if (existing != null && existing.IsLocked)
                {
                    throw new InvalidOperationException(
                        "Layer '" + AlignmentLayerName + "' is locked.");
                }

                return existingId;
            }

            layers.UpgradeOpen();
            var layer = new LayerTableRecord
            {
                Name = AlignmentLayerName
            };
            ObjectId layerId = layers.Add(layer);
            transaction.AddNewlyCreatedDBObject(layer, true);
            return layerId;
        }

        private static ObjectId GetOrCreateLayer(
            Database database,
            Transaction transaction,
            string requestedLayerName)
        {
            string layerName = NormalizeBranchLayerName(requestedLayerName);
            LayerTable layers = (LayerTable)transaction.GetObject(
                database.LayerTableId,
                OpenMode.ForRead,
                false);
            if (layers.Has(layerName))
            {
                ObjectId existingId = layers[layerName];
                LayerTableRecord existing = transaction.GetObject(
                    existingId,
                    OpenMode.ForRead,
                    false) as LayerTableRecord;
                if (existing != null && existing.IsLocked)
                    throw new InvalidOperationException(
                        "Layer '" + layerName + "' is locked.");
                return existingId;
            }

            layers.UpgradeOpen();
            var layer = new LayerTableRecord { Name = layerName };
            ObjectId layerId = layers.Add(layer);
            transaction.AddNewlyCreatedDBObject(layer, true);
            return layerId;
        }

        private static void EnsureRegApp(
            Database database,
            Transaction transaction)
        {
            RegAppTable applications = (RegAppTable)transaction.GetObject(
                database.RegAppTableId,
                OpenMode.ForRead,
                false);
            if (applications.Has(RegAppName))
            {
                return;
            }

            applications.UpgradeOpen();
            var record = new RegAppTableRecord
            {
                Name = RegAppName
            };
            applications.Add(record);
            transaction.AddNewlyCreatedDBObject(record, true);
        }

        private static Point3d GetMidpoint(IReadOnlyList<Point3d> points)
        {
            double totalLength = 0.0;
            for (int index = 1; index < points.Count; index++)
            {
                totalLength += points[index - 1].DistanceTo(points[index]);
            }

            double target = totalLength * 0.5;
            double travelled = 0.0;
            for (int index = 1; index < points.Count; index++)
            {
                Point3d start = points[index - 1];
                Point3d end = points[index];
                double segmentLength = start.DistanceTo(end);
                if (travelled + segmentLength >= target &&
                    segmentLength > GeometryTolerance)
                {
                    double fraction = (target - travelled) / segmentLength;
                    return start + ((end - start) * fraction);
                }

                travelled += segmentLength;
            }

            return points[points.Count / 2];
        }

        private static double GetTextHeight(Database database)
        {
            double value = database.Textsize;
            return value > 0.0 &&
                   !double.IsNaN(value) &&
                   !double.IsInfinity(value)
                ? value
                : 2.5;
        }

        private static bool Confirm(Editor editor, string message)
        {
            return DisciplineWorkflowDialogs.Confirm(
                "CE Tools - Sewer Alignments",
                message + "?");
        }

        private sealed class NetworkAlignmentPlan
        {
            public NetworkAlignmentPlan(
                ObjectId networkId,
                string networkName,
                IReadOnlyList<BranchAlignmentPlan> branches)
            {
                NetworkId = networkId;
                NetworkName = networkName ?? string.Empty;
                Branches = branches;
            }

            public ObjectId NetworkId { get; }
            public string NetworkName { get; }
            public IReadOnlyList<BranchAlignmentPlan> Branches { get; }
        }

        private sealed class BranchAlignmentPlan
        {
            public BranchAlignmentPlan(
                ObjectId networkId,
                int branchNumber,
                string startStructureName,
                IReadOnlyList<ObjectId> structureIds,
                IReadOnlyList<ObjectId> pipeIds,
                IReadOnlyList<Point3d> planPoints)
            {
                NetworkId = networkId;
                BranchNumber = branchNumber;
                StartStructureName = startStructureName ?? string.Empty;
                StructureIds = structureIds;
                PipeIds = pipeIds;
                PlanPoints = planPoints;
            }

            public ObjectId NetworkId { get; }
            public int BranchNumber { get; }
            public string BranchName =>
                "Branch-" + BranchNumber.ToString(CultureInfo.InvariantCulture);
            public string StartStructureName { get; }
            public IReadOnlyList<ObjectId> StructureIds { get; }
            public IReadOnlyList<ObjectId> PipeIds { get; }
            public IReadOnlyList<Point3d> PlanPoints { get; }
        }

        private struct StructureSortKey
        {
            public StructureSortKey(
                int branch,
                int sequence)
            {
                Branch = branch;
                Sequence = sequence;
            }

            public int Branch { get; private set; }
            public int Sequence { get; private set; }
        }

        private sealed class BranchPipeRecord
        {
            public BranchPipeRecord(
                ObjectId pipeId,
                ObjectId startStructureId,
                ObjectId endStructureId,
                int sequenceNumber)
            {
                PipeId = pipeId;
                StartStructureId = startStructureId;
                EndStructureId = endStructureId;
                SequenceNumber = sequenceNumber;
            }

            public ObjectId PipeId { get; }
            public ObjectId StartStructureId { get; }
            public ObjectId EndStructureId { get; }
            public int SequenceNumber { get; }

            public ObjectId Other(ObjectId structureId)
            {
                if (structureId == StartStructureId)
                {
                    return EndStructureId;
                }

                if (structureId == EndStructureId)
                {
                    return StartStructureId;
                }

                throw new InvalidOperationException(
                    "A branch pipe was queried from a structure it does not connect.");
            }
        }
    }
}
