<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/CE.Tools.Civil3D/AssemblyTemplateCatalog.cs" Link="AssemblyTemplateCatalog.cs" />
  </ItemGroup>
</Project>
