#!/usr/bin/env python3
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'src'/'CE.Tools.Civil3D'/'PluginEntry.cs'
t=p.read_text(encoding='utf-8')

def rep(old,new):
 global t
 if old not in t: raise SystemExit('PluginEntry marker missing: '+old[:180])
 t=t.replace(old,new,1)

rep('''                        Cmd("Phase 1 Utilities", "CE_PHASE1 ", "Open every original CE Tools Phase 1 utility family in one visual hub."),\n                        Cmd("Project Setup", "CE_PROJECTSETUP ", "Create or update project metadata and review it in a pop-up."),''',
'''                        Cmd("Phase 1 Utilities", "CE_PHASE1 ", "Open every original CE Tools Phase 1 utility family in one visual hub."),\n                        Cmd("Project Coordination", "CE_PROJECTCOORDINATION ", "Coordinate discipline XREFs, paper-space page setups and survey/map location tools."),\n                        Cmd("Cadastral Utility Planner", "CE_UTILITYPLANNER ", "Prepare linked cadastral utility routes, constraints, planning manhole points and downstream Sewer/SW/Water workflows."),\n                        Cmd("Project Setup", "CE_PROJECTSETUP ", "Create or update project metadata and review it in a pop-up."),''')
rep('''                        Cmd("Coordinate System Tools", "CE_COORDSYS ", "Open the coordinate-system menu."),\n                        Cmd("Information", "CE_COORDSYSINFO ", "Report the current coordinate system."),''',
'''                        Cmd("Coordinate System Tools", "CE_COORDSYS ", "Open the coordinate-system menu."),\n                        Cmd("Survey Location and Coordinate System", "CE_SURVEYLOCATION ", "Choose a Namibian project town and assign the matching installed Autodesk LO system when available."),\n                        Cmd("Latitude / Longitude Map Tools", "CE_MAPLOCATION ", "Open entered WGS84 latitude/longitude in Google Maps or Google Earth without changing drawing geometry."),\n                        Cmd("Information", "CE_COORDSYSINFO ", "Report the current coordinate system."),''')
rep('''                        Cmd("Open Workflow Centre", "CE_TOOLSPALETTE ", "Open every ribbon workflow and searchable command in the floating window."),\n                        Cmd("Phase 1 Utilities", "CE_PHASE1 ", "Open the completed Phase 1 utility hub."),''',
'''                        Cmd("Open Workflow Centre", "CE_TOOLSPALETTE ", "Open every ribbon workflow and searchable command in the floating window."),\n                        Cmd("Create Coordinated Master XREF Drawing", "CE_MASTERXREF ", "Create a new non-destructive master DWG referencing Roads, Stormwater, Sewer and Water source drawings at the same origin."),\n                        Cmd("Multi-Layout Page Setup Manager", "CE_PAGESETUPMANAGER ", "Copy one paper-space layout page setup to multiple layouts in a popup workflow."),\n                        Cmd("Phase 1 Utilities", "CE_PHASE1 ", "Open the completed Phase 1 utility hub."),''')
rep('''                Row(\n                    Menu(\n                        "CE_TOOLS_STORMWATER_MENU",''',
'''                Row(\n                    Menu(\n                        "CE_TOOLS_UTILITY_PLANNER_MENU",\n                        "Utility\\nPlanning",\n                        "Cadastral route preparation, constraints and linked discipline-production handoff.",\n                        Cmd("Cadastral Utility Planner", "CE_UTILITYPLANNER ", "Open cadastral route preparation and downstream network workflows."),\n                        Cmd("Create Linked Cadastral Routes", "CE_UTILITYROUTES ", "Create inward-offset utility planning routes, manhole planning points and a constraint report."),\n                        Cmd("Refresh Linked Cadastral Routes", "CE_UTILITYROUTESREFRESH ", "Refresh utility routes from edited source erf/cadastral polylines."),\n                        Cmd("Prepare Crossings and Junctions", "CE_PLBREAKJUNCTIONS ", "Break prepared utility polylines at true crossings and T-junctions.")),\n                    Menu(\n                        "CE_TOOLS_STORMWATER_MENU",''')
p.write_text(t,encoding='utf-8')
print('Coordination and utility ribbon entries applied.')