#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'src'/'CE.Tools.Civil3D'

def patch(name, old, new, count=1):
    p=SRC/name; t=p.read_text(encoding='utf-8')
    if t.count(old) < count: raise SystemExit(f'{name}: marker missing: {old[:180]}')
    p.write_text(t.replace(old,new,count),encoding='utf-8')

# Surface repair: adaptive retry when the original neighbourhood is too small.
patch('SurfaceSpikeHoleRepairCommands.cs',
'''            settings.AddChoice(\n                "HoleHandling",''',
'''            settings.AddChoice(\n                "AdaptiveSearch",\n                "Repair Criteria",\n                "Adaptive neighbour retry",\n                "Yes",\n                "If the first local search finds no repair candidates, retry with a wider neighbourhood before reporting no repair.",\n                new[] { "Yes", "No" });\n            settings.AddChoice(\n                "HoleHandling",''')
patch('SurfaceSpikeHoleRepairCommands.cs',
'''            bool fillHoles = !string.Equals(\n                settings.Text("HoleHandling"),''',
'''            bool adaptiveSearch = string.Equals(\n                settings.Text("AdaptiveSearch"),\n                "Yes",\n                StringComparison.OrdinalIgnoreCase);\n            bool fillHoles = !string.Equals(\n                settings.Text("HoleHandling"),''')
patch('SurfaceSpikeHoleRepairCommands.cs',
'''                plan = BuildPlan(\n                    document.Database,\n                    sourceId,\n                    spikeTolerance,\n                    neighbourRadius,\n                    minimumNeighbours,\n                    fillHoles);''',
'''                plan = BuildPlan(\n                    document.Database,\n                    sourceId,\n                    spikeTolerance,\n                    neighbourRadius,\n                    minimumNeighbours,\n                    fillHoles);\n                if (adaptiveSearch &&\n                    plan.Replacements.Count == 0 &&\n                    plan.HoleFillPoints.Count == 0)\n                {\n                    RepairPlan retry = BuildPlan(\n                        document.Database,\n                        sourceId,\n                        spikeTolerance,\n                        neighbourRadius * 4.0,\n                        Math.Max(2, minimumNeighbours - 2),\n                        fillHoles);\n                    if (retry.Replacements.Count > 0 || retry.HoleFillPoints.Count > 0)\n                    {\n                        plan = retry;\n                        document.Editor.WriteMessage(\n                            "\\nCE_SURFSPIKEHOLEFIX: the initial local search found no candidates; adaptive search expanded the neighbour radius to {0:N2} m.",\n                            neighbourRadius * 4.0);\n                    }\n                }''')
patch('SurfaceSpikeHoleRepairCommands.cs',
'''            ShowPreview(document, plan);\n            document.Editor.WriteMessage(''',
'''            if (plan.Replacements.Count == 0 && plan.HoleFillPoints.Count == 0)\n            {\n                document.Editor.WriteMessage(\n                    "\\nCE_SURFSPIKEHOLEFIX: no spike/low or internal-hole repair candidates were found with the selected criteria. No unchanged repair surface was created.");\n                return;\n            }\n\n            ShowPreview(document, plan);\n            document.Editor.WriteMessage(''')
patch('SurfaceSpikeHoleRepairCommands.cs',
'''                AddPoints(generated, plan.OutputPoints);\n                generated.XData = new ResultBuffer(''',
'''                AddPoints(generated, plan.OutputPoints);\n                Rebuild(generated);\n                int generatedVertexCount = ReadVertices(generated).Count;\n                if (generatedVertexCount < 3)\n                    throw new InvalidOperationException(\n                        "The repaired TIN did not rebuild with readable vertices; no output surface will be committed.");\n                generated.XData = new ResultBuffer(''')

# Network schedules: verify suspicious 1 m lengths against actual endpoint geometry.
patch('NetworkAssetScheduleCommands.cs',
'''            double? length = ReadDouble(value,\n                "Length3DCenterToCenter",\n                "Length2DCenterToCenter",\n                "Length3D",\n                "Length2D",\n                "Length");''',
'''            double? length = ReadDouble(value,\n                "Length3DCenterToCenter",\n                "Length2DCenterToCenter",\n                "Length3D",\n                "Length2D",\n                "Length");\n            double? geometricLength = ReadGeometricLength(value);\n            if (geometricLength.HasValue && geometricLength.Value > 0.001 &&\n                (!length.HasValue || length.Value <= 0.0 ||\n                 (Math.Abs(length.Value - 1.0) < 0.001 && geometricLength.Value > 1.01)))\n                length = geometricLength;''')
patch('NetworkAssetScheduleCommands.cs',
'''        private static string FormatDiameter(object value)\n        {\n            double? diameter = ReadDouble(value,\n                "InnerDiameterOrWidth",\n                "InnerDiameter",\n                "NominalDiameter",\n                "Diameter");\n            double? height = ReadDouble(value,\n                "InnerHeight",\n                "InnerDiameterOrHeight",\n                "Height");\n            if (!diameter.HasValue) return string.Empty;\n            if (height.HasValue && Math.Abs(height.Value - diameter.Value) > 0.000001)\n                return diameter.Value.ToString("N3", CultureInfo.CurrentCulture) + " × " +\n                    height.Value.ToString("N3", CultureInfo.CurrentCulture);\n            return diameter.Value.ToString("N3", CultureInfo.CurrentCulture);\n        }''',
'''        private static string FormatDiameter(object value)\n        {\n            double? diameter = ReadDouble(value,\n                "InnerDiameterOrWidth",\n                "InnerDiameter",\n                "NominalDiameter",\n                "Diameter");\n            double? height = ReadDouble(value,\n                "InnerHeight",\n                "InnerDiameterOrHeight",\n                "Height");\n            if (!diameter.HasValue) return string.Empty;\n            double widthMm = ToNominalMillimetres(diameter.Value);\n            if (height.HasValue && Math.Abs(height.Value - diameter.Value) > 0.000001)\n                return widthMm.ToString("N0", CultureInfo.CurrentCulture) + " × " +\n                    ToNominalMillimetres(height.Value).ToString("N0", CultureInfo.CurrentCulture) + " mm";\n            return widthMm.ToString("N0", CultureInfo.CurrentCulture) + " mm";\n        }\n\n        private static double ToNominalMillimetres(double value)\n        {\n            double absolute = Math.Abs(value);\n            return absolute > 0.0 && absolute < 10.0 ? value * 1000.0 : value;\n        }\n\n        private static double? ReadGeometricLength(object value)\n        {\n            if (value == null) return null;\n            try\n            {\n                MethodInfo method = value.GetType().GetMethod(\n                    "GetPointAtParam",\n                    BindingFlags.Public | BindingFlags.Instance,\n                    null,\n                    new[] { typeof(double) },\n                    null);\n                if (method == null) return null;\n                object first = method.Invoke(value, new object[] { 0.0 });\n                object second = method.Invoke(value, new object[] { 1.0 });\n                if (!(first is Autodesk.AutoCAD.Geometry.Point3d) ||\n                    !(second is Autodesk.AutoCAD.Geometry.Point3d)) return null;\n                return ((Autodesk.AutoCAD.Geometry.Point3d)first).DistanceTo(\n                    (Autodesk.AutoCAD.Geometry.Point3d)second);\n            }\n            catch\n            {\n                return null;\n            }\n        }''')
print('Surface repair and network data fixes applied.')